// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"
	"database/sql"
)

const countByLoginType = `-- name: CountByLoginType :one
SELECT count(*) FROM login_user WHERE login_type = ?
`

func (q *Queries) CountByLoginType(ctx context.Context, loginType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByLoginType, loginType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsByUsername = `-- name: ExistsByUsername :one
SELECT count(*) FROM login_user WHERE username = ?
`

func (q *Queries) ExistsByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findUserByExternalIdAndLoginType = `-- name: FindUserByExternalIdAndLoginType :one
SELECT id, username, password, is_first_user, login_type, external_id, last_login_at, role
FROM login_user
WHERE external_id = ? AND login_type = ?
LIMIT 1
`

type FindUserByExternalIdAndLoginTypeParams struct {
	ExternalID sql.NullString `json:"external_id"`
	LoginType  string         `json:"login_type"`
}

func (q *Queries) FindUserByExternalIdAndLoginType(ctx context.Context, arg FindUserByExternalIdAndLoginTypeParams) (LoginUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByExternalIdAndLoginType, arg.ExternalID, arg.LoginType)
	var i LoginUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsFirstUser,
		&i.LoginType,
		&i.ExternalID,
		&i.LastLoginAt,
		&i.Role,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, password, is_first_user, login_type, external_id, last_login_at, role
FROM login_user
WHERE username = ?
LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (LoginUser, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i LoginUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsFirstUser,
		&i.LoginType,
		&i.ExternalID,
		&i.LastLoginAt,
		&i.Role,
	)
	return i, err
}

const insertLoginUser = `-- name: InsertLoginUser :exec
INSERT INTO login_user (username, password, is_first_user, login_type, external_id, last_login_at, role)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLoginUserParams struct {
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	IsFirstUser sql.NullInt64  `json:"is_first_user"`
	LoginType   string         `json:"login_type"`
	ExternalID  sql.NullString `json:"external_id"`
	LastLoginAt sql.NullString `json:"last_login_at"`
	Role        string         `json:"role"`
}

func (q *Queries) InsertLoginUser(ctx context.Context, arg InsertLoginUserParams) error {
	_, err := q.db.ExecContext(ctx, insertLoginUser,
		arg.Username,
		arg.Password,
		arg.IsFirstUser,
		arg.LoginType,
		arg.ExternalID,
		arg.LastLoginAt,
		arg.Role,
	)
	return err
}

const updateLastLoginAt = `-- name: UpdateLastLoginAt :exec
UPDATE login_user SET last_login_at = ? WHERE username = ?
`

type UpdateLastLoginAtParams struct {
	LastLoginAt sql.NullString `json:"last_login_at"`
	Username    string         `json:"username"`
}

func (q *Queries) UpdateLastLoginAt(ctx context.Context, arg UpdateLastLoginAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastLoginAt, arg.LastLoginAt, arg.Username)
	return err
}

const updateUserCredentials = `-- name: UpdateUserCredentials :exec
UPDATE login_user SET username = ?, password = ? WHERE username = ?
`

type UpdateUserCredentialsParams struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Username_2 string `json:"username_2"`
}

func (q *Queries) UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCredentials, arg.Username, arg.Password, arg.Username_2)
	return err
}
