// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ban.sql

package repo

import (
	"context"
	"database/sql"
)

const findTopBanByIpAddress = `-- name: FindTopBanByIpAddress :one
SELECT id, ip_address, source, operator_name, reason, status, create_time, unban_time, remark
FROM ban_record
WHERE ip_address = ?
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) FindTopBanByIpAddress(ctx context.Context, ipAddress string) (BanRecord, error) {
	row := q.db.QueryRowContext(ctx, findTopBanByIpAddress, ipAddress)
	var i BanRecord
	err := row.Scan(
		&i.ID,
		&i.IpAddress,
		&i.Source,
		&i.OperatorName,
		&i.Reason,
		&i.Status,
		&i.CreateTime,
		&i.UnbanTime,
		&i.Remark,
	)
	return i, err
}

const insertBan = `-- name: InsertBan :exec
INSERT INTO ban_record (ip_address, source, operator_name, reason, status, create_time)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertBanParams struct {
	IpAddress    string         `json:"ip_address"`
	Source       sql.NullString `json:"source"`
	OperatorName sql.NullString `json:"operator_name"`
	Reason       sql.NullString `json:"reason"`
	Status       int64          `json:"status"`
	CreateTime   string         `json:"create_time"`
}

func (q *Queries) InsertBan(ctx context.Context, arg InsertBanParams) error {
	_, err := q.db.ExecContext(ctx, insertBan,
		arg.IpAddress,
		arg.Source,
		arg.OperatorName,
		arg.Reason,
		arg.Status,
		arg.CreateTime,
	)
	return err
}

const updateBanStatus = `-- name: UpdateBanStatus :exec
UPDATE ban_record
SET status = ?, reason = ?, unban_time = ?, operator_name = ?
WHERE id = ?
`

type UpdateBanStatusParams struct {
	Status       int64          `json:"status"`
	Reason       sql.NullString `json:"reason"`
	UnbanTime    sql.NullString `json:"unban_time"`
	OperatorName sql.NullString `json:"operator_name"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateBanStatus(ctx context.Context, arg UpdateBanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBanStatus,
		arg.Status,
		arg.Reason,
		arg.UnbanTime,
		arg.OperatorName,
		arg.ID,
	)
	return err
}
