// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cloud_tenancy.sql

package repo

import (
	"context"
	"database/sql"
)

const findCloudTenancyByName = `-- name: FindCloudTenancyByName :one

SELECT id, tenancy_name, cloud_type, type, def_name, account_cost, create_time, update_time
FROM cloud_tenancy WHERE tenancy_name = ?
`

// Cloud tenancy queries (Phase 9). cloud_tenancy stores account cost and
// custom name per tenancy.
func (q *Queries) FindCloudTenancyByName(ctx context.Context, tenancyName string) (CloudTenancy, error) {
	row := q.db.QueryRowContext(ctx, findCloudTenancyByName, tenancyName)
	var i CloudTenancy
	err := row.Scan(
		&i.ID,
		&i.TenancyName,
		&i.CloudType,
		&i.Type,
		&i.DefName,
		&i.AccountCost,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateCloudTenancyCost = `-- name: UpdateCloudTenancyCost :exec
UPDATE cloud_tenancy SET account_cost = ?, update_time = ? WHERE tenancy_name = ?
`

type UpdateCloudTenancyCostParams struct {
	AccountCost sql.NullString `json:"account_cost"`
	UpdateTime  sql.NullString `json:"update_time"`
	TenancyName string         `json:"tenancy_name"`
}

func (q *Queries) UpdateCloudTenancyCost(ctx context.Context, arg UpdateCloudTenancyCostParams) error {
	_, err := q.db.ExecContext(ctx, updateCloudTenancyCost, arg.AccountCost, arg.UpdateTime, arg.TenancyName)
	return err
}

const upsertCloudTenancy = `-- name: UpsertCloudTenancy :exec
INSERT INTO cloud_tenancy (tenancy_name, cloud_type, type, def_name, account_cost, create_time, update_time)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tenancy_name) DO UPDATE SET
    def_name = excluded.def_name,
    account_cost = excluded.account_cost,
    update_time = excluded.update_time
`

type UpsertCloudTenancyParams struct {
	TenancyName string         `json:"tenancy_name"`
	CloudType   int64          `json:"cloud_type"`
	Type        int64          `json:"type"`
	DefName     sql.NullString `json:"def_name"`
	AccountCost sql.NullString `json:"account_cost"`
	CreateTime  sql.NullString `json:"create_time"`
	UpdateTime  sql.NullString `json:"update_time"`
}

func (q *Queries) UpsertCloudTenancy(ctx context.Context, arg UpsertCloudTenancyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCloudTenancy,
		arg.TenancyName,
		arg.CloudType,
		arg.Type,
		arg.DefName,
		arg.AccountCost,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}
