// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_receive.sql

package repo

import (
	"context"
	"database/sql"
)

const countEmailReceives = `-- name: CountEmailReceives :one
SELECT COUNT(*) FROM email_receive
WHERE (COALESCE(NULLIF(?, ''), email) = email)
  AND (COALESCE(NULLIF(?, ''), name) = name)
`

type CountEmailReceivesParams struct {
	NULLIF   interface{} `json:"NULLIF"`
	NULLIF_2 interface{} `json:"NULLIF_2"`
}

func (q *Queries) CountEmailReceives(ctx context.Context, arg CountEmailReceivesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailReceives, arg.NULLIF, arg.NULLIF_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmailReceive = `-- name: DeleteEmailReceive :exec
DELETE FROM email_receive WHERE id = ?
`

func (q *Queries) DeleteEmailReceive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailReceive, id)
	return err
}

const findEmailReceiveById = `-- name: FindEmailReceiveById :one

SELECT id, email, name, create_time, update_time
FROM email_receive WHERE id = ?
`

// Email receive (recipient) queries (Phase 12.2). email_receive stores
// email recipients for batch sending.
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) FindEmailReceiveById(ctx context.Context, id int64) (EmailReceive, error) {
	row := q.db.QueryRowContext(ctx, findEmailReceiveById, id)
	var i EmailReceive
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const insertEmailReceive = `-- name: InsertEmailReceive :exec
INSERT INTO email_receive (email, name, create_time, update_time)
VALUES (?, ?, ?, ?)
`

type InsertEmailReceiveParams struct {
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	CreateTime sql.NullString `json:"create_time"`
	UpdateTime sql.NullString `json:"update_time"`
}

func (q *Queries) InsertEmailReceive(ctx context.Context, arg InsertEmailReceiveParams) error {
	_, err := q.db.ExecContext(ctx, insertEmailReceive,
		arg.Email,
		arg.Name,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const listEmailReceives = `-- name: ListEmailReceives :many
SELECT id, email, name, create_time, update_time
FROM email_receive
WHERE (COALESCE(NULLIF(?, ''), email) = email)
  AND (COALESCE(NULLIF(?, ''), name) = name)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListEmailReceivesParams struct {
	NULLIF   interface{} `json:"NULLIF"`
	NULLIF_2 interface{} `json:"NULLIF_2"`
	Limit    int64       `json:"limit"`
	Offset   int64       `json:"offset"`
}

func (q *Queries) ListEmailReceives(ctx context.Context, arg ListEmailReceivesParams) ([]EmailReceive, error) {
	rows, err := q.db.QueryContext(ctx, listEmailReceives,
		arg.NULLIF,
		arg.NULLIF_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailReceive{}
	for rows.Next() {
		var i EmailReceive
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
