// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_send_record.sql

package repo

import (
	"context"
	"database/sql"
)

const countEmailSendRecords = `-- name: CountEmailSendRecords :one
SELECT COUNT(*) FROM email_send_record WHERE email_body_id = ?
`

func (q *Queries) CountEmailSendRecords(ctx context.Context, emailBodyID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailSendRecords, emailBodyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmailSendRecordsByBodyId = `-- name: DeleteEmailSendRecordsByBodyId :exec
DELETE FROM email_send_record WHERE email_body_id = ?
`

func (q *Queries) DeleteEmailSendRecordsByBodyId(ctx context.Context, emailBodyID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteEmailSendRecordsByBodyId, emailBodyID)
	return err
}

const deleteEmailSendRecordsByConfigId = `-- name: DeleteEmailSendRecordsByConfigId :exec
DELETE FROM email_send_record
WHERE email_body_id IN (SELECT email_body_id FROM email_body WHERE tenant_email_config_id = ?)
`

func (q *Queries) DeleteEmailSendRecordsByConfigId(ctx context.Context, tenantEmailConfigID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailSendRecordsByConfigId, tenantEmailConfigID)
	return err
}

const insertEmailSendRecord = `-- name: InsertEmailSendRecord :exec

INSERT INTO email_send_record (email_send_record_id, email_body_id,
    email_send_address, current_version, tenant_name,
    email_receive_id, receive_email_address, send_state, create_time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEmailSendRecordParams struct {
	EmailSendRecordID   sql.NullString `json:"email_send_record_id"`
	EmailBodyID         sql.NullString `json:"email_body_id"`
	EmailSendAddress    sql.NullString `json:"email_send_address"`
	CurrentVersion      sql.NullInt64  `json:"current_version"`
	TenantName          sql.NullString `json:"tenant_name"`
	EmailReceiveID      sql.NullInt64  `json:"email_receive_id"`
	ReceiveEmailAddress sql.NullString `json:"receive_email_address"`
	SendState           sql.NullInt64  `json:"send_state"`
	CreateTime          sql.NullString `json:"create_time"`
}

// Email send record queries (Phase 12.2). email_send_record tracks per-recipient
// send results for each email body batch.
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) InsertEmailSendRecord(ctx context.Context, arg InsertEmailSendRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertEmailSendRecord,
		arg.EmailSendRecordID,
		arg.EmailBodyID,
		arg.EmailSendAddress,
		arg.CurrentVersion,
		arg.TenantName,
		arg.EmailReceiveID,
		arg.ReceiveEmailAddress,
		arg.SendState,
		arg.CreateTime,
	)
	return err
}

const listEmailSendRecords = `-- name: ListEmailSendRecords :many
SELECT id, email_send_record_id, email_body_id, email_send_address,
    current_version, tenant_name, email_receive_id,
    receive_email_address, send_state, create_time
FROM email_send_record
WHERE email_body_id = ?
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListEmailSendRecordsParams struct {
	EmailBodyID sql.NullString `json:"email_body_id"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

func (q *Queries) ListEmailSendRecords(ctx context.Context, arg ListEmailSendRecordsParams) ([]EmailSendRecord, error) {
	rows, err := q.db.QueryContext(ctx, listEmailSendRecords, arg.EmailBodyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailSendRecord{}
	for rows.Next() {
		var i EmailSendRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmailSendRecordID,
			&i.EmailBodyID,
			&i.EmailSendAddress,
			&i.CurrentVersion,
			&i.TenantName,
			&i.EmailReceiveID,
			&i.ReceiveEmailAddress,
			&i.SendState,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailSendRecordState = `-- name: UpdateEmailSendRecordState :exec
UPDATE email_send_record SET send_state = ? WHERE email_send_record_id = ?
`

type UpdateEmailSendRecordStateParams struct {
	SendState         sql.NullInt64  `json:"send_state"`
	EmailSendRecordID sql.NullString `json:"email_send_record_id"`
}

func (q *Queries) UpdateEmailSendRecordState(ctx context.Context, arg UpdateEmailSendRecordStateParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailSendRecordState, arg.SendState, arg.EmailSendRecordID)
	return err
}
