// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_body.sql

package repo

import (
	"context"
	"database/sql"
)

const countEmailBodies = `-- name: CountEmailBodies :one
SELECT COUNT(*) FROM email_body
WHERE (COALESCE(NULLIF(?, ''), email_body_id) = email_body_id)
`

func (q *Queries) CountEmailBodies(ctx context.Context, nullif interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailBodies, nullif)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmailBodiesByConfigId = `-- name: DeleteEmailBodiesByConfigId :exec
DELETE FROM email_body WHERE tenant_email_config_id = ?
`

func (q *Queries) DeleteEmailBodiesByConfigId(ctx context.Context, tenantEmailConfigID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailBodiesByConfigId, tenantEmailConfigID)
	return err
}

const deleteEmailBody = `-- name: DeleteEmailBody :exec
DELETE FROM email_body WHERE email_body_id = ?
`

func (q *Queries) DeleteEmailBody(ctx context.Context, emailBodyID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailBody, emailBodyID)
	return err
}

const findEmailBodyById = `-- name: FindEmailBodyById :one
SELECT id, email_body_id, current_version, tenant_name,
    tenant_email_config_id, sender_email, title, content,
    receive_total, receive_success_total, receive_fail_total, create_time
FROM email_body WHERE email_body_id = ?
`

func (q *Queries) FindEmailBodyById(ctx context.Context, emailBodyID string) (EmailBody, error) {
	row := q.db.QueryRowContext(ctx, findEmailBodyById, emailBodyID)
	var i EmailBody
	err := row.Scan(
		&i.ID,
		&i.EmailBodyID,
		&i.CurrentVersion,
		&i.TenantName,
		&i.TenantEmailConfigID,
		&i.SenderEmail,
		&i.Title,
		&i.Content,
		&i.ReceiveTotal,
		&i.ReceiveSuccessTotal,
		&i.ReceiveFailTotal,
		&i.CreateTime,
	)
	return i, err
}

const insertEmailBody = `-- name: InsertEmailBody :exec

INSERT INTO email_body (email_body_id, current_version, tenant_name,
    tenant_email_config_id, sender_email, title, content,
    receive_total, receive_success_total, receive_fail_total, create_time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEmailBodyParams struct {
	EmailBodyID         string         `json:"email_body_id"`
	CurrentVersion      sql.NullInt64  `json:"current_version"`
	TenantName          sql.NullString `json:"tenant_name"`
	TenantEmailConfigID sql.NullInt64  `json:"tenant_email_config_id"`
	SenderEmail         sql.NullString `json:"sender_email"`
	Title               sql.NullString `json:"title"`
	Content             sql.NullString `json:"content"`
	ReceiveTotal        sql.NullInt64  `json:"receive_total"`
	ReceiveSuccessTotal sql.NullInt64  `json:"receive_success_total"`
	ReceiveFailTotal    sql.NullInt64  `json:"receive_fail_total"`
	CreateTime          sql.NullString `json:"create_time"`
}

// Email body (batch) queries (Phase 12.2). email_body tracks email batch
// send operations with aggregated success/fail counts.
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) InsertEmailBody(ctx context.Context, arg InsertEmailBodyParams) error {
	_, err := q.db.ExecContext(ctx, insertEmailBody,
		arg.EmailBodyID,
		arg.CurrentVersion,
		arg.TenantName,
		arg.TenantEmailConfigID,
		arg.SenderEmail,
		arg.Title,
		arg.Content,
		arg.ReceiveTotal,
		arg.ReceiveSuccessTotal,
		arg.ReceiveFailTotal,
		arg.CreateTime,
	)
	return err
}

const listEmailBodies = `-- name: ListEmailBodies :many
SELECT id, email_body_id, current_version, tenant_name,
    tenant_email_config_id, sender_email, title, content,
    receive_total, receive_success_total, receive_fail_total, create_time
FROM email_body
WHERE (COALESCE(NULLIF(?, ''), email_body_id) = email_body_id)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListEmailBodiesParams struct {
	NULLIF interface{} `json:"NULLIF"`
	Limit  int64       `json:"limit"`
	Offset int64       `json:"offset"`
}

func (q *Queries) ListEmailBodies(ctx context.Context, arg ListEmailBodiesParams) ([]EmailBody, error) {
	rows, err := q.db.QueryContext(ctx, listEmailBodies, arg.NULLIF, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailBody{}
	for rows.Next() {
		var i EmailBody
		if err := rows.Scan(
			&i.ID,
			&i.EmailBodyID,
			&i.CurrentVersion,
			&i.TenantName,
			&i.TenantEmailConfigID,
			&i.SenderEmail,
			&i.Title,
			&i.Content,
			&i.ReceiveTotal,
			&i.ReceiveSuccessTotal,
			&i.ReceiveFailTotal,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailBodyTotals = `-- name: UpdateEmailBodyTotals :exec
UPDATE email_body SET receive_success_total = ?, receive_fail_total = ?
WHERE email_body_id = ?
`

type UpdateEmailBodyTotalsParams struct {
	ReceiveSuccessTotal sql.NullInt64 `json:"receive_success_total"`
	ReceiveFailTotal    sql.NullInt64 `json:"receive_fail_total"`
	EmailBodyID         string        `json:"email_body_id"`
}

func (q *Queries) UpdateEmailBodyTotals(ctx context.Context, arg UpdateEmailBodyTotalsParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailBodyTotals, arg.ReceiveSuccessTotal, arg.ReceiveFailTotal, arg.EmailBodyID)
	return err
}
