// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grabber.sql

package repo

import (
	"context"
	"database/sql"
)

const advanceNextExecutionTime = `-- name: AdvanceNextExecutionTime :exec
UPDATE boot_instance SET next_execution_time = ? WHERE id = ?
`

type AdvanceNextExecutionTimeParams struct {
	NextExecutionTime sql.NullString `json:"next_execution_time"`
	ID                int64          `json:"id"`
}

func (q *Queries) AdvanceNextExecutionTime(ctx context.Context, arg AdvanceNextExecutionTimeParams) error {
	_, err := q.db.ExecContext(ctx, advanceNextExecutionTime, arg.NextExecutionTime, arg.ID)
	return err
}

const deleteLock = `-- name: DeleteLock :exec
DELETE FROM open_boot_lock WHERE task_id = ?
`

func (q *Queries) DeleteLock(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteLock, taskID)
	return err
}

const deleteProcessingLocks = `-- name: DeleteProcessingLocks :exec
DELETE FROM open_boot_lock WHERE status = 'PROCESSING'
`

func (q *Queries) DeleteProcessingLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteProcessingLocks)
	return err
}

const findBootInstanceByID = `-- name: FindBootInstanceByID :one
SELECT id, version, boot_id, tenant_id, ocpu, memory, disk, loop_time, instance_count, status, architecture, root_password, public_ip, next_execution_time, add_count, success_count, remark, created_at, updated_at, cloud_type, current_attempt_count, yesterday_attempt_count, reset_today_flag, last_reset_date, fail_count, total_count, image_id, operating_system, operating_system_version, data_gap, notify_flag FROM boot_instance WHERE id = ?
`

func (q *Queries) FindBootInstanceByID(ctx context.Context, id int64) (BootInstance, error) {
	row := q.db.QueryRowContext(ctx, findBootInstanceByID, id)
	var i BootInstance
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.BootID,
		&i.TenantID,
		&i.Ocpu,
		&i.Memory,
		&i.Disk,
		&i.LoopTime,
		&i.InstanceCount,
		&i.Status,
		&i.Architecture,
		&i.RootPassword,
		&i.PublicIp,
		&i.NextExecutionTime,
		&i.AddCount,
		&i.SuccessCount,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloudType,
		&i.CurrentAttemptCount,
		&i.YesterdayAttemptCount,
		&i.ResetTodayFlag,
		&i.LastResetDate,
		&i.FailCount,
		&i.TotalCount,
		&i.ImageID,
		&i.OperatingSystem,
		&i.OperatingSystemVersion,
		&i.DataGap,
		&i.NotifyFlag,
	)
	return i, err
}

const findComputerInfoByBootIDStr = `-- name: FindComputerInfoByBootIDStr :one

SELECT id, boot_id_str, computer_create_json, tenant_id, architecture, cloud_type, computer_region FROM oci_computer_info WHERE boot_id_str = ?
`

// oci_computer_info queries (Phase 5, placeholder)
func (q *Queries) FindComputerInfoByBootIDStr(ctx context.Context, bootIDStr sql.NullString) (OciComputerInfo, error) {
	row := q.db.QueryRowContext(ctx, findComputerInfoByBootIDStr, bootIDStr)
	var i OciComputerInfo
	err := row.Scan(
		&i.ID,
		&i.BootIDStr,
		&i.ComputerCreateJson,
		&i.TenantID,
		&i.Architecture,
		&i.CloudType,
		&i.ComputerRegion,
	)
	return i, err
}

const findDistinctTasksToExecute = `-- name: FindDistinctTasksToExecute :many

SELECT b.id, b.boot_id, b.tenant_id, b.ocpu, b.memory, b.disk, b.loop_time,
       b.instance_count, b.status, b.architecture, b.root_password, b.public_ip,
       b.next_execution_time, b.add_count, b.success_count, b.remark,
       b.created_at, b.updated_at, b.cloud_type, b.current_attempt_count,
       b.yesterday_attempt_count, b.reset_today_flag, b.last_reset_date,
       b.fail_count, b.total_count, b.image_id, b.operating_system,
       b.operating_system_version, b.data_gap, b.notify_flag
FROM boot_instance b
WHERE b.status = 1 AND b.next_execution_time <= ?1
  AND b.next_execution_time = (
      SELECT MIN(b2.next_execution_time)
      FROM boot_instance b2
      WHERE b2.status = 1
        AND b2.tenant_id = b.tenant_id
        AND COALESCE(b2.architecture, '') = COALESCE(b.architecture, '')
        AND b2.next_execution_time <= ?1
  )
ORDER BY b.next_execution_time ASC
LIMIT ?2
`

type FindDistinctTasksToExecuteParams struct {
	Now   sql.NullString `json:"now"`
	Limit int64          `json:"limit"`
}

type FindDistinctTasksToExecuteRow struct {
	ID                     int64          `json:"id"`
	BootID                 sql.NullString `json:"boot_id"`
	TenantID               sql.NullInt64  `json:"tenant_id"`
	Ocpu                   sql.NullInt64  `json:"ocpu"`
	Memory                 sql.NullInt64  `json:"memory"`
	Disk                   sql.NullInt64  `json:"disk"`
	LoopTime               sql.NullInt64  `json:"loop_time"`
	InstanceCount          sql.NullInt64  `json:"instance_count"`
	Status                 sql.NullInt64  `json:"status"`
	Architecture           sql.NullString `json:"architecture"`
	RootPassword           sql.NullString `json:"root_password"`
	PublicIp               sql.NullString `json:"public_ip"`
	NextExecutionTime      sql.NullString `json:"next_execution_time"`
	AddCount               sql.NullInt64  `json:"add_count"`
	SuccessCount           sql.NullInt64  `json:"success_count"`
	Remark                 sql.NullString `json:"remark"`
	CreatedAt              sql.NullString `json:"created_at"`
	UpdatedAt              sql.NullString `json:"updated_at"`
	CloudType              sql.NullInt64  `json:"cloud_type"`
	CurrentAttemptCount    sql.NullInt64  `json:"current_attempt_count"`
	YesterdayAttemptCount  sql.NullInt64  `json:"yesterday_attempt_count"`
	ResetTodayFlag         sql.NullInt64  `json:"reset_today_flag"`
	LastResetDate          sql.NullString `json:"last_reset_date"`
	FailCount              sql.NullInt64  `json:"fail_count"`
	TotalCount             sql.NullInt64  `json:"total_count"`
	ImageID                sql.NullString `json:"image_id"`
	OperatingSystem        sql.NullString `json:"operating_system"`
	OperatingSystemVersion sql.NullString `json:"operating_system_version"`
	DataGap                sql.NullString `json:"data_gap"`
	NotifyFlag             sql.NullString `json:"notify_flag"`
}

// Grabber queries (Phase 4). boot_instance, open_boot_lock, oci_computer_info,
// boot_total_instance. See SPEC S8; parity with BootInstanceRepository +
// OpenBootLockRepository + BootTotalInstanceService queries.
func (q *Queries) FindDistinctTasksToExecute(ctx context.Context, arg FindDistinctTasksToExecuteParams) ([]FindDistinctTasksToExecuteRow, error) {
	rows, err := q.db.QueryContext(ctx, findDistinctTasksToExecute, arg.Now, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDistinctTasksToExecuteRow{}
	for rows.Next() {
		var i FindDistinctTasksToExecuteRow
		if err := rows.Scan(
			&i.ID,
			&i.BootID,
			&i.TenantID,
			&i.Ocpu,
			&i.Memory,
			&i.Disk,
			&i.LoopTime,
			&i.InstanceCount,
			&i.Status,
			&i.Architecture,
			&i.RootPassword,
			&i.PublicIp,
			&i.NextExecutionTime,
			&i.AddCount,
			&i.SuccessCount,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloudType,
			&i.CurrentAttemptCount,
			&i.YesterdayAttemptCount,
			&i.ResetTodayFlag,
			&i.LastResetDate,
			&i.FailCount,
			&i.TotalCount,
			&i.ImageID,
			&i.OperatingSystem,
			&i.OperatingSystemVersion,
			&i.DataGap,
			&i.NotifyFlag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLockByTaskID = `-- name: FindLockByTaskID :one
SELECT task_id, cloud_type, status, ins_id, create_time FROM open_boot_lock WHERE task_id = ?
`

func (q *Queries) FindLockByTaskID(ctx context.Context, taskID string) (OpenBootLock, error) {
	row := q.db.QueryRowContext(ctx, findLockByTaskID, taskID)
	var i OpenBootLock
	err := row.Scan(
		&i.TaskID,
		&i.CloudType,
		&i.Status,
		&i.InsID,
		&i.CreateTime,
	)
	return i, err
}

const incrementFailCount = `-- name: IncrementFailCount :exec
UPDATE boot_instance SET fail_count = fail_count + 1 WHERE id = ?
`

func (q *Queries) IncrementFailCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementFailCount, id)
	return err
}

const insertLockIgnore = `-- name: InsertLockIgnore :exec

INSERT OR IGNORE INTO open_boot_lock (task_id, cloud_type, status, create_time)
VALUES (?, 1, 'PROCESSING', ?)
`

type InsertLockIgnoreParams struct {
	TaskID     string         `json:"task_id"`
	CreateTime sql.NullString `json:"create_time"`
}

// open_boot_lock queries
func (q *Queries) InsertLockIgnore(ctx context.Context, arg InsertLockIgnoreParams) error {
	_, err := q.db.ExecContext(ctx, insertLockIgnore, arg.TaskID, arg.CreateTime)
	return err
}

const markNotificationAsSent = `-- name: MarkNotificationAsSent :exec
UPDATE boot_instance SET notify_flag = 'YES' WHERE id = ? AND notify_flag = 'NO'
`

func (q *Queries) MarkNotificationAsSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsSent, id)
	return err
}

const updateBootInstanceStatus = `-- name: UpdateBootInstanceStatus :exec
UPDATE boot_instance SET status = ?, public_ip = ?, updated_at = ? WHERE id = ?
`

type UpdateBootInstanceStatusParams struct {
	Status    sql.NullInt64  `json:"status"`
	PublicIp  sql.NullString `json:"public_ip"`
	UpdatedAt sql.NullString `json:"updated_at"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateBootInstanceStatus(ctx context.Context, arg UpdateBootInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBootInstanceStatus,
		arg.Status,
		arg.PublicIp,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLockSuccess = `-- name: UpdateLockSuccess :exec
UPDATE open_boot_lock SET status = 'SUCCESS', ins_id = ? WHERE task_id = ?
`

type UpdateLockSuccessParams struct {
	InsID  sql.NullString `json:"ins_id"`
	TaskID string         `json:"task_id"`
}

func (q *Queries) UpdateLockSuccess(ctx context.Context, arg UpdateLockSuccessParams) error {
	_, err := q.db.ExecContext(ctx, updateLockSuccess, arg.InsID, arg.TaskID)
	return err
}
