// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: image_cache.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteImageCacheByTenant = `-- name: DeleteImageCacheByTenant :exec
DELETE FROM image_cache WHERE tenant_id = ?
`

func (q *Queries) DeleteImageCacheByTenant(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImageCacheByTenant, tenantID)
	return err
}

const listImageCacheByTenant = `-- name: ListImageCacheByTenant :many
SELECT id, tenant_id, compartment_id, image_id, display_name,
       operating_system, operating_system_version, architecture,
       size_in_gbs, launch_mode, time_created,
       last_synced_at, cloud_type
FROM image_cache
WHERE tenant_id = ?
ORDER BY operating_system, operating_system_version
`

func (q *Queries) ListImageCacheByTenant(ctx context.Context, tenantID int64) ([]ImageCache, error) {
	rows, err := q.db.QueryContext(ctx, listImageCacheByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageCache{}
	for rows.Next() {
		var i ImageCache
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompartmentID,
			&i.ImageID,
			&i.DisplayName,
			&i.OperatingSystem,
			&i.OperatingSystemVersion,
			&i.Architecture,
			&i.SizeInGbs,
			&i.LaunchMode,
			&i.TimeCreated,
			&i.LastSyncedAt,
			&i.CloudType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageCacheByTenantAndArch = `-- name: ListImageCacheByTenantAndArch :many
SELECT id, tenant_id, compartment_id, image_id, display_name,
       operating_system, operating_system_version, architecture,
       size_in_gbs, launch_mode, time_created,
       last_synced_at, cloud_type
FROM image_cache
WHERE tenant_id = ? AND architecture = ?
ORDER BY operating_system, operating_system_version
`

type ListImageCacheByTenantAndArchParams struct {
	TenantID     int64  `json:"tenant_id"`
	Architecture string `json:"architecture"`
}

func (q *Queries) ListImageCacheByTenantAndArch(ctx context.Context, arg ListImageCacheByTenantAndArchParams) ([]ImageCache, error) {
	rows, err := q.db.QueryContext(ctx, listImageCacheByTenantAndArch, arg.TenantID, arg.Architecture)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageCache{}
	for rows.Next() {
		var i ImageCache
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompartmentID,
			&i.ImageID,
			&i.DisplayName,
			&i.OperatingSystem,
			&i.OperatingSystemVersion,
			&i.Architecture,
			&i.SizeInGbs,
			&i.LaunchMode,
			&i.TimeCreated,
			&i.LastSyncedAt,
			&i.CloudType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImageCacheByTenantAndOS = `-- name: ListImageCacheByTenantAndOS :many
SELECT id, tenant_id, compartment_id, image_id, display_name,
       operating_system, operating_system_version, architecture,
       size_in_gbs, launch_mode, time_created,
       last_synced_at, cloud_type
FROM image_cache
WHERE tenant_id = ? AND operating_system LIKE ?
ORDER BY operating_system_version
`

type ListImageCacheByTenantAndOSParams struct {
	TenantID        int64          `json:"tenant_id"`
	OperatingSystem sql.NullString `json:"operating_system"`
}

func (q *Queries) ListImageCacheByTenantAndOS(ctx context.Context, arg ListImageCacheByTenantAndOSParams) ([]ImageCache, error) {
	rows, err := q.db.QueryContext(ctx, listImageCacheByTenantAndOS, arg.TenantID, arg.OperatingSystem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageCache{}
	for rows.Next() {
		var i ImageCache
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompartmentID,
			&i.ImageID,
			&i.DisplayName,
			&i.OperatingSystem,
			&i.OperatingSystemVersion,
			&i.Architecture,
			&i.SizeInGbs,
			&i.LaunchMode,
			&i.TimeCreated,
			&i.LastSyncedAt,
			&i.CloudType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImageCache = `-- name: UpsertImageCache :exec
INSERT INTO image_cache (
    tenant_id, compartment_id, image_id, display_name,
    operating_system, operating_system_version, architecture,
    size_in_gbs, launch_mode, time_created,
    last_synced_at, cloud_type
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, 1
)
`

type UpsertImageCacheParams struct {
	TenantID               int64          `json:"tenant_id"`
	CompartmentID          string         `json:"compartment_id"`
	ImageID                string         `json:"image_id"`
	DisplayName            sql.NullString `json:"display_name"`
	OperatingSystem        sql.NullString `json:"operating_system"`
	OperatingSystemVersion sql.NullString `json:"operating_system_version"`
	Architecture           string         `json:"architecture"`
	SizeInGbs              sql.NullInt64  `json:"size_in_gbs"`
	LaunchMode             sql.NullString `json:"launch_mode"`
	TimeCreated            sql.NullString `json:"time_created"`
	LastSyncedAt           string         `json:"last_synced_at"`
}

func (q *Queries) UpsertImageCache(ctx context.Context, arg UpsertImageCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertImageCache,
		arg.TenantID,
		arg.CompartmentID,
		arg.ImageID,
		arg.DisplayName,
		arg.OperatingSystem,
		arg.OperatingSystemVersion,
		arg.Architecture,
		arg.SizeInGbs,
		arg.LaunchMode,
		arg.TimeCreated,
		arg.LastSyncedAt,
	)
	return err
}
