// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_detail_ext.sql

package repo

import (
	"context"
	"database/sql"
)

const countInstanceDetails = `-- name: CountInstanceDetails :one
SELECT COUNT(*) FROM instance_detail
`

func (q *Queries) CountInstanceDetails(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInstanceDetails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInstanceBackupDetail = `-- name: DeleteInstanceBackupDetail :exec
DELETE FROM instance_backup_detail WHERE id = ?
`

func (q *Queries) DeleteInstanceBackupDetail(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInstanceBackupDetail, id)
	return err
}

const deleteInstanceTrafficByTenantId = `-- name: DeleteInstanceTrafficByTenantId :exec
DELETE FROM instance_traffic WHERE tenant_id = ?
`

func (q *Queries) DeleteInstanceTrafficByTenantId(ctx context.Context, tenantID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteInstanceTrafficByTenantId, tenantID)
	return err
}

const findInstanceBackupsByTenantId = `-- name: FindInstanceBackupsByTenantId :many

SELECT id, tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
       boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
       compartment_id, boot_volume_id, remark, boot_volume_name, ipv6_addresses,
       username, port, password, processor_description, architecture, cloud_type,
       sys_image_backup
FROM instance_backup_detail WHERE tenant_id = ? ORDER BY id DESC
`

// instance_backup_detail queries
func (q *Queries) FindInstanceBackupsByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]InstanceBackupDetail, error) {
	rows, err := q.db.QueryContext(ctx, findInstanceBackupsByTenantId, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceBackupDetail{}
	for rows.Next() {
		var i InstanceBackupDetail
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstanceID,
			&i.DisplayName,
			&i.Shape,
			&i.State,
			&i.Ocpus,
			&i.MemoryInGbs,
			&i.BootVolumeSizeInGbs,
			&i.PublicIps,
			&i.PrivateIps,
			&i.AvailabilityDomain,
			&i.CompartmentID,
			&i.BootVolumeID,
			&i.Remark,
			&i.BootVolumeName,
			&i.Ipv6Addresses,
			&i.Username,
			&i.Port,
			&i.Password,
			&i.ProcessorDescription,
			&i.Architecture,
			&i.CloudType,
			&i.SysImageBackup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInstanceDetailByID = `-- name: FindInstanceDetailByID :one

SELECT id, tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
       boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
       compartment_id, boot_volume_id, boot_volume_name, vpus_per_gb,
       ipv6_addresses, vnic_ids, username, port, password,
       processor_description, architecture, cloud_type, sys_image_backup,
       conn_time, enable_ping, on_line_enable, last_on_line_enable,
       offline_notify, resume_notify, monitor_installed, last_heartbeat, create_time
FROM instance_detail WHERE id = ?
`

type FindInstanceDetailByIDRow struct {
	ID                   int64          `json:"id"`
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	VpusPerGb            sql.NullString `json:"vpus_per_gb"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	VnicIds              sql.NullString `json:"vnic_ids"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
	ConnTime             int64          `json:"conn_time"`
	EnablePing           int64          `json:"enable_ping"`
	OnLineEnable         int64          `json:"on_line_enable"`
	LastOnLineEnable     int64          `json:"last_on_line_enable"`
	OfflineNotify        int64          `json:"offline_notify"`
	ResumeNotify         int64          `json:"resume_notify"`
	MonitorInstalled     sql.NullInt64  `json:"monitor_installed"`
	LastHeartbeat        sql.NullString `json:"last_heartbeat"`
	CreateTime           sql.NullString `json:"create_time"`
}

// Extended instance_detail queries (Phase 5). Instance management, traffic,
// backup records. ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) FindInstanceDetailByID(ctx context.Context, id int64) (FindInstanceDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findInstanceDetailByID, id)
	var i FindInstanceDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InstanceID,
		&i.DisplayName,
		&i.Shape,
		&i.State,
		&i.Ocpus,
		&i.MemoryInGbs,
		&i.BootVolumeSizeInGbs,
		&i.PublicIps,
		&i.PrivateIps,
		&i.AvailabilityDomain,
		&i.CompartmentID,
		&i.BootVolumeID,
		&i.BootVolumeName,
		&i.VpusPerGb,
		&i.Ipv6Addresses,
		&i.VnicIds,
		&i.Username,
		&i.Port,
		&i.Password,
		&i.ProcessorDescription,
		&i.Architecture,
		&i.CloudType,
		&i.SysImageBackup,
		&i.ConnTime,
		&i.EnablePing,
		&i.OnLineEnable,
		&i.LastOnLineEnable,
		&i.OfflineNotify,
		&i.ResumeNotify,
		&i.MonitorInstalled,
		&i.LastHeartbeat,
		&i.CreateTime,
	)
	return i, err
}

const findInstanceTrafficByInstanceId = `-- name: FindInstanceTrafficByInstanceId :many

SELECT id, instance_id, tenant_id, tenancy, ingress_bytes, egress_bytes,
       stats_date, last_updated, region, threshold, auto_shutdown, created_at, cloud_type, alert_sent
FROM instance_traffic WHERE instance_id = ? ORDER BY stats_date DESC LIMIT ?
`

type FindInstanceTrafficByInstanceIdParams struct {
	InstanceID sql.NullString `json:"instance_id"`
	Limit      int64          `json:"limit"`
}

// instance_traffic queries
func (q *Queries) FindInstanceTrafficByInstanceId(ctx context.Context, arg FindInstanceTrafficByInstanceIdParams) ([]InstanceTraffic, error) {
	rows, err := q.db.QueryContext(ctx, findInstanceTrafficByInstanceId, arg.InstanceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceTraffic{}
	for rows.Next() {
		var i InstanceTraffic
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.TenantID,
			&i.Tenancy,
			&i.IngressBytes,
			&i.EgressBytes,
			&i.StatsDate,
			&i.LastUpdated,
			&i.Region,
			&i.Threshold,
			&i.AutoShutdown,
			&i.CreatedAt,
			&i.CloudType,
			&i.AlertSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInstancesByTenantId = `-- name: FindInstancesByTenantId :many
SELECT id, tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
       boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
       compartment_id, boot_volume_id, boot_volume_name, vpus_per_gb,
       ipv6_addresses, vnic_ids, username, port, password,
       processor_description, architecture, cloud_type, sys_image_backup,
       conn_time, enable_ping, on_line_enable, last_on_line_enable,
       offline_notify, resume_notify, monitor_installed, last_heartbeat, create_time
FROM instance_detail WHERE tenant_id = ?
ORDER BY create_time DESC
`

type FindInstancesByTenantIdRow struct {
	ID                   int64          `json:"id"`
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	VpusPerGb            sql.NullString `json:"vpus_per_gb"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	VnicIds              sql.NullString `json:"vnic_ids"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
	ConnTime             int64          `json:"conn_time"`
	EnablePing           int64          `json:"enable_ping"`
	OnLineEnable         int64          `json:"on_line_enable"`
	LastOnLineEnable     int64          `json:"last_on_line_enable"`
	OfflineNotify        int64          `json:"offline_notify"`
	ResumeNotify         int64          `json:"resume_notify"`
	MonitorInstalled     sql.NullInt64  `json:"monitor_installed"`
	LastHeartbeat        sql.NullString `json:"last_heartbeat"`
	CreateTime           sql.NullString `json:"create_time"`
}

func (q *Queries) FindInstancesByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]FindInstancesByTenantIdRow, error) {
	rows, err := q.db.QueryContext(ctx, findInstancesByTenantId, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindInstancesByTenantIdRow{}
	for rows.Next() {
		var i FindInstancesByTenantIdRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstanceID,
			&i.DisplayName,
			&i.Shape,
			&i.State,
			&i.Ocpus,
			&i.MemoryInGbs,
			&i.BootVolumeSizeInGbs,
			&i.PublicIps,
			&i.PrivateIps,
			&i.AvailabilityDomain,
			&i.CompartmentID,
			&i.BootVolumeID,
			&i.BootVolumeName,
			&i.VpusPerGb,
			&i.Ipv6Addresses,
			&i.VnicIds,
			&i.Username,
			&i.Port,
			&i.Password,
			&i.ProcessorDescription,
			&i.Architecture,
			&i.CloudType,
			&i.SysImageBackup,
			&i.ConnTime,
			&i.EnablePing,
			&i.OnLineEnable,
			&i.LastOnLineEnable,
			&i.OfflineNotify,
			&i.ResumeNotify,
			&i.MonitorInstalled,
			&i.LastHeartbeat,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOfflineInstances = `-- name: FindOfflineInstances :many
SELECT id, tenant_id, instance_id, display_name, public_ips, last_heartbeat, on_line_enable
FROM instance_detail
WHERE on_line_enable = 1 AND last_heartbeat IS NOT NULL AND last_heartbeat <> '' AND last_heartbeat < ?
`

type FindOfflineInstancesRow struct {
	ID            int64          `json:"id"`
	TenantID      sql.NullInt64  `json:"tenant_id"`
	InstanceID    sql.NullString `json:"instance_id"`
	DisplayName   sql.NullString `json:"display_name"`
	PublicIps     sql.NullString `json:"public_ips"`
	LastHeartbeat sql.NullString `json:"last_heartbeat"`
	OnLineEnable  int64          `json:"on_line_enable"`
}

func (q *Queries) FindOfflineInstances(ctx context.Context, lastHeartbeat sql.NullString) ([]FindOfflineInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, findOfflineInstances, lastHeartbeat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOfflineInstancesRow{}
	for rows.Next() {
		var i FindOfflineInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstanceID,
			&i.DisplayName,
			&i.PublicIps,
			&i.LastHeartbeat,
			&i.OnLineEnable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTrafficAlertByTenantId = `-- name: FindTrafficAlertByTenantId :one

SELECT id, tenant_id, tenancy, threshold, auto_shutdown, notification_email,
       enabled, last_notification, created_at, updated_at, statistics_enabled, cloud_type
FROM traffic_alert WHERE tenant_id = ?
`

// traffic_alert queries
func (q *Queries) FindTrafficAlertByTenantId(ctx context.Context, tenantID int64) (TrafficAlert, error) {
	row := q.db.QueryRowContext(ctx, findTrafficAlertByTenantId, tenantID)
	var i TrafficAlert
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Tenancy,
		&i.Threshold,
		&i.AutoShutdown,
		&i.NotificationEmail,
		&i.Enabled,
		&i.LastNotification,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StatisticsEnabled,
		&i.CloudType,
	)
	return i, err
}

const insertInstanceBackupDetail = `-- name: InsertInstanceBackupDetail :exec
INSERT INTO instance_backup_detail (
    tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
    boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
    compartment_id, boot_volume_id, remark, boot_volume_name, ipv6_addresses,
    username, port, password, processor_description, architecture, cloud_type,
    sys_image_backup
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInstanceBackupDetailParams struct {
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	Remark               sql.NullString `json:"remark"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
}

func (q *Queries) InsertInstanceBackupDetail(ctx context.Context, arg InsertInstanceBackupDetailParams) error {
	_, err := q.db.ExecContext(ctx, insertInstanceBackupDetail,
		arg.TenantID,
		arg.InstanceID,
		arg.DisplayName,
		arg.Shape,
		arg.State,
		arg.Ocpus,
		arg.MemoryInGbs,
		arg.BootVolumeSizeInGbs,
		arg.PublicIps,
		arg.PrivateIps,
		arg.AvailabilityDomain,
		arg.CompartmentID,
		arg.BootVolumeID,
		arg.Remark,
		arg.BootVolumeName,
		arg.Ipv6Addresses,
		arg.Username,
		arg.Port,
		arg.Password,
		arg.ProcessorDescription,
		arg.Architecture,
		arg.CloudType,
		arg.SysImageBackup,
	)
	return err
}

const insertInstanceTraffic = `-- name: InsertInstanceTraffic :exec
INSERT INTO instance_traffic (
    instance_id, tenant_id, tenancy, ingress_bytes, egress_bytes, stats_date,
    region, threshold, auto_shutdown, cloud_type, alert_sent, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInstanceTrafficParams struct {
	InstanceID   sql.NullString  `json:"instance_id"`
	TenantID     sql.NullInt64   `json:"tenant_id"`
	Tenancy      sql.NullString  `json:"tenancy"`
	IngressBytes sql.NullFloat64 `json:"ingress_bytes"`
	EgressBytes  sql.NullFloat64 `json:"egress_bytes"`
	StatsDate    sql.NullString  `json:"stats_date"`
	Region       sql.NullString  `json:"region"`
	Threshold    sql.NullFloat64 `json:"threshold"`
	AutoShutdown sql.NullInt64   `json:"auto_shutdown"`
	CloudType    sql.NullInt64   `json:"cloud_type"`
	AlertSent    sql.NullInt64   `json:"alert_sent"`
	CreatedAt    sql.NullString  `json:"created_at"`
}

func (q *Queries) InsertInstanceTraffic(ctx context.Context, arg InsertInstanceTrafficParams) error {
	_, err := q.db.ExecContext(ctx, insertInstanceTraffic,
		arg.InstanceID,
		arg.TenantID,
		arg.Tenancy,
		arg.IngressBytes,
		arg.EgressBytes,
		arg.StatsDate,
		arg.Region,
		arg.Threshold,
		arg.AutoShutdown,
		arg.CloudType,
		arg.AlertSent,
		arg.CreatedAt,
	)
	return err
}

const listAllInstanceDetails = `-- name: ListAllInstanceDetails :many
SELECT id, tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
       boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
       compartment_id, boot_volume_id, boot_volume_name, vpus_per_gb,
       ipv6_addresses, vnic_ids, username, port, password,
       processor_description, architecture, cloud_type, sys_image_backup,
       conn_time, enable_ping, on_line_enable, last_on_line_enable,
       offline_notify, resume_notify, monitor_installed, last_heartbeat, create_time
FROM instance_detail
ORDER BY create_time DESC
LIMIT ? OFFSET ?
`

type ListAllInstanceDetailsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllInstanceDetailsRow struct {
	ID                   int64          `json:"id"`
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	VpusPerGb            sql.NullString `json:"vpus_per_gb"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	VnicIds              sql.NullString `json:"vnic_ids"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
	ConnTime             int64          `json:"conn_time"`
	EnablePing           int64          `json:"enable_ping"`
	OnLineEnable         int64          `json:"on_line_enable"`
	LastOnLineEnable     int64          `json:"last_on_line_enable"`
	OfflineNotify        int64          `json:"offline_notify"`
	ResumeNotify         int64          `json:"resume_notify"`
	MonitorInstalled     sql.NullInt64  `json:"monitor_installed"`
	LastHeartbeat        sql.NullString `json:"last_heartbeat"`
	CreateTime           sql.NullString `json:"create_time"`
}

func (q *Queries) ListAllInstanceDetails(ctx context.Context, arg ListAllInstanceDetailsParams) ([]ListAllInstanceDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllInstanceDetails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllInstanceDetailsRow{}
	for rows.Next() {
		var i ListAllInstanceDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstanceID,
			&i.DisplayName,
			&i.Shape,
			&i.State,
			&i.Ocpus,
			&i.MemoryInGbs,
			&i.BootVolumeSizeInGbs,
			&i.PublicIps,
			&i.PrivateIps,
			&i.AvailabilityDomain,
			&i.CompartmentID,
			&i.BootVolumeID,
			&i.BootVolumeName,
			&i.VpusPerGb,
			&i.Ipv6Addresses,
			&i.VnicIds,
			&i.Username,
			&i.Port,
			&i.Password,
			&i.ProcessorDescription,
			&i.Architecture,
			&i.CloudType,
			&i.SysImageBackup,
			&i.ConnTime,
			&i.EnablePing,
			&i.OnLineEnable,
			&i.LastOnLineEnable,
			&i.OfflineNotify,
			&i.ResumeNotify,
			&i.MonitorInstalled,
			&i.LastHeartbeat,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficAlerts = `-- name: ListTrafficAlerts :many
SELECT id, tenant_id, tenancy, threshold, auto_shutdown, notification_email,
       enabled, last_notification, created_at, updated_at, statistics_enabled, cloud_type
FROM traffic_alert ORDER BY tenant_id
`

func (q *Queries) ListTrafficAlerts(ctx context.Context) ([]TrafficAlert, error) {
	rows, err := q.db.QueryContext(ctx, listTrafficAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficAlert{}
	for rows.Next() {
		var i TrafficAlert
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Tenancy,
			&i.Threshold,
			&i.AutoShutdown,
			&i.NotificationEmail,
			&i.Enabled,
			&i.LastNotification,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StatisticsEnabled,
			&i.CloudType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstanceConnTime = `-- name: UpdateInstanceConnTime :exec
UPDATE instance_detail SET conn_time = ?, last_heartbeat = ? WHERE id = ?
`

type UpdateInstanceConnTimeParams struct {
	ConnTime      int64          `json:"conn_time"`
	LastHeartbeat sql.NullString `json:"last_heartbeat"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateInstanceConnTime(ctx context.Context, arg UpdateInstanceConnTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceConnTime, arg.ConnTime, arg.LastHeartbeat, arg.ID)
	return err
}

const updateInstanceDetailRemark = `-- name: UpdateInstanceDetailRemark :exec
UPDATE instance_detail SET remark = ? WHERE id = ?
`

type UpdateInstanceDetailRemarkParams struct {
	Remark sql.NullString `json:"remark"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateInstanceDetailRemark(ctx context.Context, arg UpdateInstanceDetailRemarkParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceDetailRemark, arg.Remark, arg.ID)
	return err
}

const updateInstanceOffline = `-- name: UpdateInstanceOffline :exec
UPDATE instance_detail SET on_line_enable = ?, offline_notify = ? WHERE id = ?
`

type UpdateInstanceOfflineParams struct {
	OnLineEnable  int64 `json:"on_line_enable"`
	OfflineNotify int64 `json:"offline_notify"`
	ID            int64 `json:"id"`
}

func (q *Queries) UpdateInstanceOffline(ctx context.Context, arg UpdateInstanceOfflineParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceOffline, arg.OnLineEnable, arg.OfflineNotify, arg.ID)
	return err
}

const updateInstanceResumeNotify = `-- name: UpdateInstanceResumeNotify :exec
UPDATE instance_detail SET resume_notify = 0, on_line_enable = 1 WHERE id = ?
`

func (q *Queries) UpdateInstanceResumeNotify(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateInstanceResumeNotify, id)
	return err
}

const upsertTrafficAlert = `-- name: UpsertTrafficAlert :exec
INSERT INTO traffic_alert (
    tenant_id, tenancy, threshold, auto_shutdown, notification_email, enabled, cloud_type,
    statistics_enabled, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tenant_id) DO UPDATE SET
    threshold = excluded.threshold,
    auto_shutdown = excluded.auto_shutdown,
    notification_email = excluded.notification_email,
    enabled = excluded.enabled,
    statistics_enabled = excluded.statistics_enabled,
    updated_at = excluded.updated_at
`

type UpsertTrafficAlertParams struct {
	TenantID          int64          `json:"tenant_id"`
	Tenancy           string         `json:"tenancy"`
	Threshold         float64        `json:"threshold"`
	AutoShutdown      int64          `json:"auto_shutdown"`
	NotificationEmail sql.NullString `json:"notification_email"`
	Enabled           int64          `json:"enabled"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	StatisticsEnabled int64          `json:"statistics_enabled"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         sql.NullString `json:"updated_at"`
}

func (q *Queries) UpsertTrafficAlert(ctx context.Context, arg UpsertTrafficAlertParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrafficAlert,
		arg.TenantID,
		arg.Tenancy,
		arg.Threshold,
		arg.AutoShutdown,
		arg.NotificationEmail,
		arg.Enabled,
		arg.CloudType,
		arg.StatisticsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
