// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_detail.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteInstanceDetailsByTenantId = `-- name: DeleteInstanceDetailsByTenantId :exec

DELETE FROM instance_detail WHERE tenant_id = ?
`

// instance_detail queries (Phase 3 instance sync). Sync is delete-by-tenant
// then insert-all (parity with Java syncOci: deleteByTenantId then saveAll).
func (q *Queries) DeleteInstanceDetailsByTenantId(ctx context.Context, tenantID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteInstanceDetailsByTenantId, tenantID)
	return err
}

const findCompartmentID = `-- name: FindCompartmentID :one
SELECT compartment_id FROM instance_detail WHERE instance_id = ? LIMIT 1
`

// Replaces the inline compartment_id lookup in wsHub.Console.SetDeps
// GetCompartmentID.
func (q *Queries) FindCompartmentID(ctx context.Context, instanceID sql.NullString) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, findCompartmentID, instanceID)
	var compartment_id sql.NullString
	err := row.Scan(&compartment_id)
	return compartment_id, err
}

const findConsoleInstanceInfo = `-- name: FindConsoleInstanceInfo :one
SELECT instance_id, display_name, public_ips, private_ips, shape,
       username, port, password, tenant_id, compartment_id, availability_domain
FROM instance_detail WHERE instance_id = ? LIMIT 1
`

type FindConsoleInstanceInfoRow struct {
	InstanceID         sql.NullString `json:"instance_id"`
	DisplayName        sql.NullString `json:"display_name"`
	PublicIps          sql.NullString `json:"public_ips"`
	PrivateIps         sql.NullString `json:"private_ips"`
	Shape              sql.NullString `json:"shape"`
	Username           sql.NullString `json:"username"`
	Port               sql.NullInt64  `json:"port"`
	Password           sql.NullString `json:"password"`
	TenantID           sql.NullInt64  `json:"tenant_id"`
	CompartmentID      sql.NullString `json:"compartment_id"`
	AvailabilityDomain sql.NullString `json:"availability_domain"`
}

// Replaces the inline SELECT in cmd/oci-start/main.go wsHub.Console.SetDeps.
// Returns the columns the console closure scans: instance_id, display_name,
// public_ips, private_ips, shape, username, port, password, tenant_id,
// compartment_id, availability_domain.
func (q *Queries) FindConsoleInstanceInfo(ctx context.Context, instanceID sql.NullString) (FindConsoleInstanceInfoRow, error) {
	row := q.db.QueryRowContext(ctx, findConsoleInstanceInfo, instanceID)
	var i FindConsoleInstanceInfoRow
	err := row.Scan(
		&i.InstanceID,
		&i.DisplayName,
		&i.PublicIps,
		&i.PrivateIps,
		&i.Shape,
		&i.Username,
		&i.Port,
		&i.Password,
		&i.TenantID,
		&i.CompartmentID,
		&i.AvailabilityDomain,
	)
	return i, err
}

const findRescueInstanceInfo = `-- name: FindRescueInstanceInfo :one
SELECT instance_id, display_name, state, boot_volume_id, shape,
       availability_domain, compartment_id, public_ips, username, password
FROM instance_detail WHERE instance_id = ? LIMIT 1
`

type FindRescueInstanceInfoRow struct {
	InstanceID         sql.NullString `json:"instance_id"`
	DisplayName        sql.NullString `json:"display_name"`
	State              sql.NullString `json:"state"`
	BootVolumeID       sql.NullString `json:"boot_volume_id"`
	Shape              sql.NullString `json:"shape"`
	AvailabilityDomain sql.NullString `json:"availability_domain"`
	CompartmentID      sql.NullString `json:"compartment_id"`
	PublicIps          sql.NullString `json:"public_ips"`
	Username           sql.NullString `json:"username"`
	Password           sql.NullString `json:"password"`
}

// Replaces the inline SELECT in cmd/oci-start/main.go wsHub.Rescue.SetDeps.
// Returns: instance_id, display_name, state, boot_volume_id, shape,
// availability_domain, compartment_id, public_ips, username, password.
func (q *Queries) FindRescueInstanceInfo(ctx context.Context, instanceID sql.NullString) (FindRescueInstanceInfoRow, error) {
	row := q.db.QueryRowContext(ctx, findRescueInstanceInfo, instanceID)
	var i FindRescueInstanceInfoRow
	err := row.Scan(
		&i.InstanceID,
		&i.DisplayName,
		&i.State,
		&i.BootVolumeID,
		&i.Shape,
		&i.AvailabilityDomain,
		&i.CompartmentID,
		&i.PublicIps,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const insertInstanceDetail = `-- name: InsertInstanceDetail :exec
INSERT INTO instance_detail (
    tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
    boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
    compartment_id, boot_volume_id, boot_volume_name, vpus_per_gb,
    ipv6_addresses, vnic_ids, username, port, password,
    processor_description, architecture, cloud_type, create_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInstanceDetailParams struct {
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	VpusPerGb            sql.NullString `json:"vpus_per_gb"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	VnicIds              sql.NullString `json:"vnic_ids"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	CreateTime           sql.NullString `json:"create_time"`
}

func (q *Queries) InsertInstanceDetail(ctx context.Context, arg InsertInstanceDetailParams) error {
	_, err := q.db.ExecContext(ctx, insertInstanceDetail,
		arg.TenantID,
		arg.InstanceID,
		arg.DisplayName,
		arg.Shape,
		arg.State,
		arg.Ocpus,
		arg.MemoryInGbs,
		arg.BootVolumeSizeInGbs,
		arg.PublicIps,
		arg.PrivateIps,
		arg.AvailabilityDomain,
		arg.CompartmentID,
		arg.BootVolumeID,
		arg.BootVolumeName,
		arg.VpusPerGb,
		arg.Ipv6Addresses,
		arg.VnicIds,
		arg.Username,
		arg.Port,
		arg.Password,
		arg.ProcessorDescription,
		arg.Architecture,
		arg.CloudType,
		arg.CreateTime,
	)
	return err
}

const listInstanceDetailsByTenantId = `-- name: ListInstanceDetailsByTenantId :many
SELECT
    id, tenant_id, instance_id, display_name, shape, state, ocpus, memory_in_gbs,
    boot_volume_size_in_gbs, public_ips, private_ips, availability_domain,
    compartment_id, boot_volume_id, boot_volume_name, vpus_per_gb,
    ipv6_addresses, vnic_ids, username, port, password,
    processor_description, architecture, cloud_type, sys_image_backup,
    conn_time, enable_ping, on_line_enable, last_on_line_enable,
    offline_notify, resume_notify, monitor_installed, last_heartbeat, create_time
FROM instance_detail
WHERE tenant_id = ?
ORDER BY id
`

type ListInstanceDetailsByTenantIdRow struct {
	ID                   int64          `json:"id"`
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	VpusPerGb            sql.NullString `json:"vpus_per_gb"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	VnicIds              sql.NullString `json:"vnic_ids"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
	ConnTime             int64          `json:"conn_time"`
	EnablePing           int64          `json:"enable_ping"`
	OnLineEnable         int64          `json:"on_line_enable"`
	LastOnLineEnable     int64          `json:"last_on_line_enable"`
	OfflineNotify        int64          `json:"offline_notify"`
	ResumeNotify         int64          `json:"resume_notify"`
	MonitorInstalled     sql.NullInt64  `json:"monitor_installed"`
	LastHeartbeat        sql.NullString `json:"last_heartbeat"`
	CreateTime           sql.NullString `json:"create_time"`
}

func (q *Queries) ListInstanceDetailsByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]ListInstanceDetailsByTenantIdRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceDetailsByTenantId, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceDetailsByTenantIdRow{}
	for rows.Next() {
		var i ListInstanceDetailsByTenantIdRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InstanceID,
			&i.DisplayName,
			&i.Shape,
			&i.State,
			&i.Ocpus,
			&i.MemoryInGbs,
			&i.BootVolumeSizeInGbs,
			&i.PublicIps,
			&i.PrivateIps,
			&i.AvailabilityDomain,
			&i.CompartmentID,
			&i.BootVolumeID,
			&i.BootVolumeName,
			&i.VpusPerGb,
			&i.Ipv6Addresses,
			&i.VnicIds,
			&i.Username,
			&i.Port,
			&i.Password,
			&i.ProcessorDescription,
			&i.Architecture,
			&i.CloudType,
			&i.SysImageBackup,
			&i.ConnTime,
			&i.EnablePing,
			&i.OnLineEnable,
			&i.LastOnLineEnable,
			&i.OfflineNotify,
			&i.ResumeNotify,
			&i.MonitorInstalled,
			&i.LastHeartbeat,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
