// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql"
)

type AiChatHistory struct {
	ID        int64          `json:"id"`
	UserID    string         `json:"user_id"`
	Role      string         `json:"role"`
	Content   string         `json:"content"`
	ModelID   sql.NullString `json:"model_id"`
	CreatedAt string         `json:"created_at"`
}

type ApiCache struct {
	CacheKey   string `json:"cache_key"`
	CacheValue string `json:"cache_value"`
	ExpiresAt  string `json:"expires_at"`
	UpdatedAt  string `json:"updated_at"`
}

type AppMessage struct {
	ID          int64          `json:"id"`
	BusinessID  sql.NullString `json:"business_id"`
	MessageType sql.NullString `json:"message_type"`
	ReadStatus  sql.NullInt64  `json:"read_status"`
	Subject     sql.NullString `json:"subject"`
	ContentText sql.NullString `json:"content_text"`
	UpdateTime  sql.NullString `json:"update_time"`
	CreateTime  sql.NullString `json:"create_time"`
}

type AppVersion struct {
	ID             int64  `json:"id"`
	CurrentVersion string `json:"current_version"`
	LatestVersion  string `json:"latest_version"`
	DeployType     string `json:"deploy_type"`
	CreateTime     string `json:"create_time"`
	UpdateTime     string `json:"update_time"`
}

type BanRecord struct {
	ID           int64          `json:"id"`
	IpAddress    string         `json:"ip_address"`
	Source       sql.NullString `json:"source"`
	OperatorName sql.NullString `json:"operator_name"`
	Reason       sql.NullString `json:"reason"`
	Status       int64          `json:"status"`
	CreateTime   string         `json:"create_time"`
	UnbanTime    sql.NullString `json:"unban_time"`
	Remark       sql.NullString `json:"remark"`
}

type BootInstance struct {
	ID                     int64          `json:"id"`
	Version                int64          `json:"version"`
	BootID                 sql.NullString `json:"boot_id"`
	TenantID               sql.NullInt64  `json:"tenant_id"`
	Ocpu                   sql.NullInt64  `json:"ocpu"`
	Memory                 sql.NullInt64  `json:"memory"`
	Disk                   sql.NullInt64  `json:"disk"`
	LoopTime               sql.NullInt64  `json:"loop_time"`
	InstanceCount          sql.NullInt64  `json:"instance_count"`
	Status                 sql.NullInt64  `json:"status"`
	Architecture           sql.NullString `json:"architecture"`
	RootPassword           sql.NullString `json:"root_password"`
	PublicIp               sql.NullString `json:"public_ip"`
	NextExecutionTime      sql.NullString `json:"next_execution_time"`
	AddCount               sql.NullInt64  `json:"add_count"`
	SuccessCount           sql.NullInt64  `json:"success_count"`
	Remark                 sql.NullString `json:"remark"`
	CreatedAt              sql.NullString `json:"created_at"`
	UpdatedAt              sql.NullString `json:"updated_at"`
	CloudType              sql.NullInt64  `json:"cloud_type"`
	CurrentAttemptCount    sql.NullInt64  `json:"current_attempt_count"`
	YesterdayAttemptCount  sql.NullInt64  `json:"yesterday_attempt_count"`
	ResetTodayFlag         sql.NullInt64  `json:"reset_today_flag"`
	LastResetDate          sql.NullString `json:"last_reset_date"`
	FailCount              sql.NullInt64  `json:"fail_count"`
	TotalCount             sql.NullInt64  `json:"total_count"`
	ImageID                sql.NullString `json:"image_id"`
	OperatingSystem        sql.NullString `json:"operating_system"`
	OperatingSystemVersion sql.NullString `json:"operating_system_version"`
	DataGap                sql.NullString `json:"data_gap"`
	NotifyFlag             sql.NullString `json:"notify_flag"`
}

type ChatAiConfig struct {
	ID                 int64          `json:"id"`
	Version            int64          `json:"version"`
	TenantID           sql.NullString `json:"tenant_id"`
	ModelID            sql.NullString `json:"model_id"`
	ShowModelID        sql.NullString `json:"show_model_id"`
	CloudType          sql.NullInt64  `json:"cloud_type"`
	ModelName          sql.NullString `json:"model_name"`
	Provider           sql.NullString `json:"provider"`
	ApiKey             sql.NullString `json:"api_key"`
	BaseUrl            sql.NullString `json:"base_url"`
	Enabled            sql.NullInt64  `json:"enabled"`
	SystemPrompt       sql.NullString `json:"system_prompt"`
	MaxTokens          sql.NullInt64  `json:"max_tokens"`
	Temperature        sql.NullString `json:"temperature"`
	MaxHistoryMessages sql.NullInt64  `json:"max_history_messages"`
	CreatedAt          sql.NullString `json:"created_at"`
	UpdatedAt          sql.NullString `json:"updated_at"`
}

type CloudSshFolder struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	ParentID  sql.NullInt64  `json:"parent_id"`
	SortOrder sql.NullInt64  `json:"sort_order"`
	CreatedAt sql.NullString `json:"created_at"`
	UpdatedAt sql.NullString `json:"updated_at"`
	Deleted   int64          `json:"deleted"`
}

type CloudTenancy struct {
	ID          int64          `json:"id"`
	TenancyName string         `json:"tenancy_name"`
	CloudType   int64          `json:"cloud_type"`
	Type        int64          `json:"type"`
	DefName     sql.NullString `json:"def_name"`
	AccountCost sql.NullString `json:"account_cost"`
	CreateTime  sql.NullString `json:"create_time"`
	UpdateTime  sql.NullString `json:"update_time"`
}

type ConsoleConnection struct {
	ID             int64          `json:"id"`
	InstanceID     string         `json:"instance_id"`
	TenantID       int64          `json:"tenant_id"`
	ConnectionID   string         `json:"connection_id"`
	PrivateKeyPath sql.NullString `json:"private_key_path"`
	CloudType      sql.NullInt64  `json:"cloud_type"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type DbConfig struct {
	ID                   int64          `json:"id"`
	TenantID             int64          `json:"tenant_id"`
	DbName               sql.NullString `json:"db_name"`
	DbPrivateUrl         sql.NullString `json:"db_private_url"`
	DbPublicUrl          sql.NullString `json:"db_public_url"`
	DbPort               sql.NullInt64  `json:"db_port"`
	DbPassword           sql.NullString `json:"db_password"`
	DbID                 sql.NullString `json:"db_id"`
	DbVersion            sql.NullString `json:"db_version"`
	DbStorageSize        sql.NullInt64  `json:"db_storage_size"`
	DbDataBaseMode       sql.NullString `json:"db_data_base_mode"`
	DbDisplayName        sql.NullString `json:"db_display_name"`
	DbShapeName          sql.NullString `json:"db_shape_name"`
	DbAvailabilityDomain sql.NullString `json:"db_availability_domain"`
	DbHighAvailable      sql.NullInt64  `json:"db_high_available"`
	DbSubnetID           sql.NullString `json:"db_subnet_id"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	DbType               sql.NullInt64  `json:"db_type"`
	DbStatus             sql.NullString `json:"db_status"`
	CreateAt             sql.NullString `json:"create_at"`
	UpdatedAt            sql.NullString `json:"updated_at"`
}

type DnsRecord struct {
	ID               int64          `json:"id"`
	ProviderType     string         `json:"provider_type"`
	DomainName       string         `json:"domain_name"`
	RecordName       string         `json:"record_name"`
	RecordType       string         `json:"record_type"`
	RecordValue      string         `json:"record_value"`
	Ttl              sql.NullInt64  `json:"ttl"`
	Priority         sql.NullInt64  `json:"priority"`
	ProviderRecordID sql.NullString `json:"provider_record_id"`
	ZoneID           sql.NullString `json:"zone_id"`
	Proxied          sql.NullInt64  `json:"proxied"`
	Status           sql.NullString `json:"status"`
	Remark           sql.NullString `json:"remark"`
	ExtraData        sql.NullString `json:"extra_data"`
	CreateTime       string         `json:"create_time"`
	UpdateTime       string         `json:"update_time"`
	LastSyncTime     sql.NullString `json:"last_sync_time"`
	Weight           sql.NullInt64  `json:"weight"`
	Type             int64          `json:"type"`
}

type EmailBody struct {
	ID                  int64          `json:"id"`
	EmailBodyID         string         `json:"email_body_id"`
	CurrentVersion      sql.NullInt64  `json:"current_version"`
	TenantName          sql.NullString `json:"tenant_name"`
	TenantEmailConfigID sql.NullInt64  `json:"tenant_email_config_id"`
	SenderEmail         sql.NullString `json:"sender_email"`
	Title               sql.NullString `json:"title"`
	Content             sql.NullString `json:"content"`
	ReceiveTotal        sql.NullInt64  `json:"receive_total"`
	ReceiveSuccessTotal sql.NullInt64  `json:"receive_success_total"`
	ReceiveFailTotal    sql.NullInt64  `json:"receive_fail_total"`
	CreateTime          sql.NullString `json:"create_time"`
}

type EmailReceive struct {
	ID         int64          `json:"id"`
	Email      string         `json:"email"`
	Name       string         `json:"name"`
	CreateTime sql.NullString `json:"create_time"`
	UpdateTime sql.NullString `json:"update_time"`
}

type EmailSendRecord struct {
	ID                  int64          `json:"id"`
	EmailSendRecordID   sql.NullString `json:"email_send_record_id"`
	EmailBodyID         sql.NullString `json:"email_body_id"`
	EmailSendAddress    sql.NullString `json:"email_send_address"`
	CurrentVersion      sql.NullInt64  `json:"current_version"`
	TenantName          sql.NullString `json:"tenant_name"`
	EmailReceiveID      sql.NullInt64  `json:"email_receive_id"`
	ReceiveEmailAddress sql.NullString `json:"receive_email_address"`
	SendState           sql.NullInt64  `json:"send_state"`
	CreateTime          sql.NullString `json:"create_time"`
}

type ImageCache struct {
	ID                     int64          `json:"id"`
	TenantID               int64          `json:"tenant_id"`
	CompartmentID          string         `json:"compartment_id"`
	ImageID                string         `json:"image_id"`
	DisplayName            sql.NullString `json:"display_name"`
	OperatingSystem        sql.NullString `json:"operating_system"`
	OperatingSystemVersion sql.NullString `json:"operating_system_version"`
	Architecture           string         `json:"architecture"`
	SizeInGbs              sql.NullInt64  `json:"size_in_gbs"`
	LaunchMode             sql.NullString `json:"launch_mode"`
	TimeCreated            sql.NullString `json:"time_created"`
	LastSyncedAt           string         `json:"last_synced_at"`
	CloudType              int64          `json:"cloud_type"`
}

type InstallApp struct {
	ID          int64          `json:"id"`
	UniqueID    string         `json:"unique_id"`
	IpAddress   string         `json:"ip_address"`
	InstallTime string         `json:"install_time"`
	CreateTime  sql.NullString `json:"create_time"`
	UpdateTime  sql.NullString `json:"update_time"`
}

type InstanceBackupDetail struct {
	ID                   int64          `json:"id"`
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	Remark               sql.NullString `json:"remark"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
}

type InstanceCloudNetwork struct {
	ID                     int64          `json:"id"`
	TenantID               sql.NullString `json:"tenant_id"`
	VcnID                  sql.NullString `json:"vcn_id"`
	VcnName                sql.NullString `json:"vcn_name"`
	SubnetID               sql.NullString `json:"subnet_id"`
	SubnetName             sql.NullString `json:"subnet_name"`
	Region                 sql.NullString `json:"region"`
	CidrBlock              sql.NullString `json:"cidr_block"`
	NetWorkSecurityGroupID sql.NullString `json:"net_work_security_group_id"`
	CreatedAt              sql.NullString `json:"created_at"`
	UpdatedAt              sql.NullString `json:"updated_at"`
	CloudType              sql.NullInt64  `json:"cloud_type"`
}

type InstanceDetail struct {
	ID                   int64          `json:"id"`
	TenantID             sql.NullInt64  `json:"tenant_id"`
	InstanceID           sql.NullString `json:"instance_id"`
	DisplayName          sql.NullString `json:"display_name"`
	Shape                sql.NullString `json:"shape"`
	State                sql.NullString `json:"state"`
	Ocpus                sql.NullInt64  `json:"ocpus"`
	MemoryInGbs          sql.NullInt64  `json:"memory_in_gbs"`
	BootVolumeSizeInGbs  sql.NullInt64  `json:"boot_volume_size_in_gbs"`
	PublicIps            sql.NullString `json:"public_ips"`
	PrivateIps           sql.NullString `json:"private_ips"`
	AvailabilityDomain   sql.NullString `json:"availability_domain"`
	CompartmentID        sql.NullString `json:"compartment_id"`
	BootVolumeID         sql.NullString `json:"boot_volume_id"`
	Remark               sql.NullString `json:"remark"`
	BootVolumeName       sql.NullString `json:"boot_volume_name"`
	VpusPerGb            sql.NullString `json:"vpus_per_gb"`
	Ipv6Addresses        sql.NullString `json:"ipv6_addresses"`
	VnicIds              sql.NullString `json:"vnic_ids"`
	Username             sql.NullString `json:"username"`
	Port                 sql.NullInt64  `json:"port"`
	Password             sql.NullString `json:"password"`
	ProcessorDescription sql.NullString `json:"processor_description"`
	Architecture         sql.NullString `json:"architecture"`
	CloudType            sql.NullInt64  `json:"cloud_type"`
	SysImageBackup       sql.NullInt64  `json:"sys_image_backup"`
	ConnTime             int64          `json:"conn_time"`
	EnablePing           int64          `json:"enable_ping"`
	OnLineEnable         int64          `json:"on_line_enable"`
	LastOnLineEnable     int64          `json:"last_on_line_enable"`
	OfflineNotify        int64          `json:"offline_notify"`
	ResumeNotify         int64          `json:"resume_notify"`
	MonitorInstalled     sql.NullInt64  `json:"monitor_installed"`
	LastHeartbeat        sql.NullString `json:"last_heartbeat"`
	CreateTime           sql.NullString `json:"create_time"`
}

type InstanceTraffic struct {
	ID           int64           `json:"id"`
	InstanceID   sql.NullString  `json:"instance_id"`
	TenantID     sql.NullInt64   `json:"tenant_id"`
	Tenancy      sql.NullString  `json:"tenancy"`
	IngressBytes sql.NullFloat64 `json:"ingress_bytes"`
	EgressBytes  sql.NullFloat64 `json:"egress_bytes"`
	StatsDate    sql.NullString  `json:"stats_date"`
	LastUpdated  sql.NullString  `json:"last_updated"`
	Region       sql.NullString  `json:"region"`
	Threshold    sql.NullFloat64 `json:"threshold"`
	AutoShutdown sql.NullInt64   `json:"auto_shutdown"`
	CreatedAt    sql.NullString  `json:"created_at"`
	CloudType    sql.NullInt64   `json:"cloud_type"`
	AlertSent    sql.NullInt64   `json:"alert_sent"`
}

type LoginSession struct {
	Token        string         `json:"token"`
	Username     string         `json:"username"`
	Ip           sql.NullString `json:"ip"`
	UserAgent    sql.NullString `json:"user_agent"`
	CreatedAt    string         `json:"created_at"`
	ExpiresAt    string         `json:"expires_at"`
	LastActiveAt string         `json:"last_active_at"`
}

type LoginUser struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	IsFirstUser sql.NullInt64  `json:"is_first_user"`
	LoginType   string         `json:"login_type"`
	ExternalID  sql.NullString `json:"external_id"`
	LastLoginAt sql.NullString `json:"last_login_at"`
	Role        string         `json:"role"`
}

type Memo struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	Content    sql.NullString `json:"content"`
	Summary    sql.NullString `json:"summary"`
	CreateTime sql.NullString `json:"create_time"`
	UpdateTime sql.NullString `json:"update_time"`
}

type OciComputerInfo struct {
	ID                 int64          `json:"id"`
	BootIDStr          sql.NullString `json:"boot_id_str"`
	ComputerCreateJson sql.NullString `json:"computer_create_json"`
	TenantID           sql.NullInt64  `json:"tenant_id"`
	Architecture       sql.NullString `json:"architecture"`
	CloudType          sql.NullInt64  `json:"cloud_type"`
	ComputerRegion     sql.NullString `json:"computer_region"`
}

type OciMultipartUploadRecord struct {
	ID             int64          `json:"id"`
	TenantID       int64          `json:"tenant_id"`
	CloudType      sql.NullInt64  `json:"cloud_type"`
	TenancyOcid    sql.NullString `json:"tenancy_ocid"`
	Namespace      sql.NullString `json:"namespace"`
	BucketName     string         `json:"bucket_name"`
	ObjectName     string         `json:"object_name"`
	UploadID       string         `json:"upload_id"`
	TotalSize      sql.NullInt64  `json:"total_size"`
	ChunkSize      sql.NullInt64  `json:"chunk_size"`
	TotalParts     sql.NullInt64  `json:"total_parts"`
	CompletedParts sql.NullString `json:"completed_parts"`
	Status         sql.NullString `json:"status"`
	CreateTime     sql.NullString `json:"create_time"`
	UpdateTime     sql.NullString `json:"update_time"`
}

type OciSshConn struct {
	ID         int64          `json:"id"`
	InstanceID sql.NullString `json:"instance_id"`
	Name       string         `json:"name"`
	Remark     string         `json:"remark"`
	Username   string         `json:"username"`
	Host       sql.NullString `json:"host"`
	Port       sql.NullInt64  `json:"port"`
	Password   sql.NullString `json:"password"`
	CloudType  sql.NullInt64  `json:"cloud_type"`
	FolderID   sql.NullInt64  `json:"folder_id"`
}

type OpenBootLock struct {
	TaskID     string         `json:"task_id"`
	CloudType  int64          `json:"cloud_type"`
	Status     string         `json:"status"`
	InsID      sql.NullString `json:"ins_id"`
	CreateTime sql.NullString `json:"create_time"`
}

type OtherBootInstance struct {
	ID            int64          `json:"id"`
	Version       int64          `json:"version"`
	BootID        sql.NullString `json:"boot_id"`
	TenantID      sql.NullInt64  `json:"tenant_id"`
	Ocpu          sql.NullInt64  `json:"ocpu"`
	Memory        sql.NullInt64  `json:"memory"`
	Disk          sql.NullInt64  `json:"disk"`
	InstanceCount sql.NullInt64  `json:"instance_count"`
	Status        sql.NullInt64  `json:"status"`
	Architecture  sql.NullString `json:"architecture"`
	RootPassword  sql.NullString `json:"root_password"`
	PublicIp      sql.NullString `json:"public_ip"`
	Remark        sql.NullString `json:"remark"`
	InstanceName  sql.NullString `json:"instance_name"`
	Zone          sql.NullString `json:"zone"`
	CreatedAt     sql.NullString `json:"created_at"`
	UpdatedAt     sql.NullString `json:"updated_at"`
	CloudType     sql.NullInt64  `json:"cloud_type"`
}

type OtpKey struct {
	ID         int64          `json:"id"`
	KeyName    sql.NullString `json:"key_name"`
	SecretKey  sql.NullString `json:"secret_key"`
	QrCode     sql.NullString `json:"qr_code"`
	Issuer     sql.NullString `json:"issuer"`
	CreateTime string         `json:"create_time"`
	UpdateTime string         `json:"update_time"`
}

type RegisterDetail struct {
	ID                     int64          `json:"id"`
	TenantPrvID            sql.NullInt64  `json:"tenant_prv_id"`
	TenantID               sql.NullString `json:"tenant_id"`
	AccountType            sql.NullInt64  `json:"account_type"`
	PlanType               sql.NullInt64  `json:"plan_type"`
	RegisterTime           sql.NullString `json:"register_time"`
	City                   sql.NullString `json:"city"`
	Country                sql.NullString `json:"country"`
	EmailAddress           sql.NullString `json:"email_address"`
	FirstName              sql.NullString `json:"first_name"`
	LastName               sql.NullString `json:"last_name"`
	Line1                  sql.NullString `json:"line1"`
	PostalCode             sql.NullString `json:"postal_code"`
	SubscriptionPlanNumber sql.NullString `json:"subscription_plan_number"`
	UpgradeState           sql.NullString `json:"upgrade_state"`
	CurrencyCode           sql.NullString `json:"currency_code"`
	IsIntentToPay          sql.NullInt64  `json:"is_intent_to_pay"`
	CreatedTime            sql.NullString `json:"created_time"`
	UpdatedTime            sql.NullString `json:"updated_time"`
	CloudType              sql.NullInt64  `json:"cloud_type"`
}

type ServerMetric struct {
	ID                   int64           `json:"id"`
	ServerID             sql.NullString  `json:"server_id"`
	ServerIp             sql.NullString  `json:"server_ip"`
	CpuUsage             sql.NullFloat64 `json:"cpu_usage"`
	MemoryUsage          sql.NullFloat64 `json:"memory_usage"`
	DiskUsage            sql.NullFloat64 `json:"disk_usage"`
	UploadTraffic        sql.NullFloat64 `json:"upload_traffic"`
	DownloadTraffic      sql.NullFloat64 `json:"download_traffic"`
	LastConnectionTime   sql.NullString  `json:"last_connection_time"`
	CpuCores             sql.NullInt64   `json:"cpu_cores"`
	TotalMemory          sql.NullFloat64 `json:"total_memory"`
	TotalDisk            sql.NullFloat64 `json:"total_disk"`
	TotalUploadTraffic   sql.NullString  `json:"total_upload_traffic"`
	TotalDownloadTraffic sql.NullString  `json:"total_download_traffic"`
}

type ShapeCache struct {
	ID                    int64           `json:"id"`
	TenantID              int64           `json:"tenant_id"`
	CompartmentID         string          `json:"compartment_id"`
	AvailabilityDomain    sql.NullString  `json:"availability_domain"`
	Shape                 string          `json:"shape"`
	Architecture          string          `json:"architecture"`
	Ocpus                 sql.NullFloat64 `json:"ocpus"`
	MemoryInGbs           sql.NullFloat64 `json:"memory_in_gbs"`
	ProcessorDescription  sql.NullString  `json:"processor_description"`
	IsFlexible            int64           `json:"is_flexible"`
	MaxVnicAttachments    sql.NullInt64   `json:"max_vnic_attachments"`
	GpuDescription        sql.NullString  `json:"gpu_description"`
	GpuCount              sql.NullInt64   `json:"gpu_count"`
	LocalDiskDescription  sql.NullString  `json:"local_disk_description"`
	NetworkingDescription sql.NullString  `json:"networking_description"`
	BaselineOcpu          sql.NullFloat64 `json:"baseline_ocpu"`
	LastSyncedAt          string          `json:"last_synced_at"`
	CloudType             int64           `json:"cloud_type"`
}

type SystemConfig struct {
	ID            int64          `json:"id"`
	ConfigKey     sql.NullString `json:"config_key"`
	ConfigValue   sql.NullString `json:"config_value"`
	ConfigEnabled sql.NullInt64  `json:"config_enabled"`
	LastModified  sql.NullString `json:"last_modified"`
}

type SystemKvStore struct {
	ID         int64          `json:"id"`
	KeyName    string         `json:"key_name"`
	LocalValue sql.NullString `json:"local_value"`
	Remark     sql.NullString `json:"remark"`
	UpdateTime sql.NullString `json:"update_time"`
	CreateTime sql.NullString `json:"create_time"`
}

type TelegramUser struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	Username     sql.NullString `json:"username"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	IsAuthorized sql.NullInt64  `json:"is_authorized"`
	Active       sql.NullInt64  `json:"active"`
	CreatedAt    string         `json:"created_at"`
	LastActiveAt sql.NullString `json:"last_active_at"`
}

type TemInstance struct {
	ID                int64          `json:"id"`
	Tenancy           sql.NullString `json:"tenancy"`
	InstanceID        sql.NullString `json:"instance_id"`
	PublicIp          sql.NullString `json:"public_ip"`
	Region            sql.NullString `json:"region"`
	Architecture      sql.NullString `json:"architecture"`
	RootPassword      sql.NullString `json:"root_password"`
	CloneBootVolumeID sql.NullString `json:"clone_boot_volume_id"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
}

type Tenant struct {
	ID                int64          `json:"id"`
	TenantID          sql.NullString `json:"tenant_id"`
	UserName          sql.NullString `json:"user_name"`
	Fingerprint       sql.NullString `json:"fingerprint"`
	Tenancy           sql.NullString `json:"tenancy"`
	Region            sql.NullString `json:"region"`
	KeyFile           sql.NullString `json:"key_file"`
	CreatedAt         sql.NullString `json:"created_at"`
	ApiSynced         sql.NullInt64  `json:"api_synced"`
	EnableIcmp        sql.NullInt64  `json:"enable_icmp"`
	EnableAllProtocol sql.NullInt64  `json:"enable_all_protocol"`
	IsHomeRegion      sql.NullInt64  `json:"is_home_region"`
	ParenID           sql.NullInt64  `json:"paren_id"`
	TenancyName       sql.NullString `json:"tenancy_name"`
	TenancyDes        sql.NullString `json:"tenancy_des"`
	AccountType       sql.NullString `json:"account_type"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	RegionEn          sql.NullString `json:"region_en"`
	IDStr             sql.NullString `json:"id_str"`
	EmailAddress      sql.NullString `json:"email_address"`
	EmailEnable       sql.NullInt64  `json:"email_enable"`
	TransferStatus    sql.NullInt64  `json:"transfer_status"`
	TransferAmount    sql.NullString `json:"transfer_amount"`
	IsActive          sql.NullInt64  `json:"is_active"`
	KeyFileBlob       sql.NullString `json:"key_file_blob"`
}

type TenantEmailConfig struct {
	ID               int64          `json:"id"`
	TenantID         sql.NullInt64  `json:"tenant_id"`
	DomainID         sql.NullString `json:"domain_id"`
	DomainName       sql.NullString `json:"domain_name"`
	SenderID         sql.NullString `json:"sender_id"`
	CredentialID     sql.NullString `json:"credential_id"`
	SmtpUsername     sql.NullString `json:"smtp_username"`
	SmtpPassword     sql.NullString `json:"smtp_password"`
	SmtpHost         sql.NullString `json:"smtp_host"`
	SmtpPort         sql.NullString `json:"smtp_port"`
	SenderEmail      sql.NullString `json:"sender_email"`
	DkimID           sql.NullString `json:"dkim_id"`
	CnameRecordValue sql.NullString `json:"cname_record_value"`
	Active           sql.NullInt64  `json:"active"`
	CreatedTime      sql.NullString `json:"created_time"`
	DailyEmailLimit  sql.NullInt64  `json:"daily_email_limit"`
	TodaySentCount   sql.NullInt64  `json:"today_sent_count"`
	LastResetDate    sql.NullString `json:"last_reset_date"`
	DbsRecordIdsStr  sql.NullString `json:"dbs_record_ids_str"`
}

type TenantSocial struct {
	ID                int64          `json:"id"`
	TenantID          sql.NullInt64  `json:"tenant_id"`
	Tenancy           sql.NullString `json:"tenancy"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	ClientID          sql.NullString `json:"client_id"`
	ClientSecret      sql.NullString `json:"client_secret"`
	SocialTypeStr     sql.NullString `json:"social_type_str"`
	ThirdLoginAddress sql.NullString `json:"third_login_address"`
	RedirectUrl       sql.NullString `json:"redirect_url"`
	SocialStatus      sql.NullString `json:"social_status"`
}

type TrafficAlert struct {
	ID                int64          `json:"id"`
	TenantID          int64          `json:"tenant_id"`
	Tenancy           string         `json:"tenancy"`
	Threshold         float64        `json:"threshold"`
	AutoShutdown      int64          `json:"auto_shutdown"`
	NotificationEmail sql.NullString `json:"notification_email"`
	Enabled           int64          `json:"enabled"`
	LastNotification  sql.NullString `json:"last_notification"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         sql.NullString `json:"updated_at"`
	StatisticsEnabled int64          `json:"statistics_enabled"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
}

type VpnProxyRecord struct {
	ID              int64          `json:"id"`
	ProxyType       string         `json:"proxy_type"`
	ProxyHost       string         `json:"proxy_host"`
	ProxyPort       int64          `json:"proxy_port"`
	ProxyUsername   sql.NullString `json:"proxy_username"`
	ProxyPassword   sql.NullString `json:"proxy_password"`
	AvailableStatus int64          `json:"available_status"`
	UpdateTime      sql.NullString `json:"update_time"`
	CreateTime      sql.NullString `json:"create_time"`
}

type VpsMonitor struct {
	ID                  int64           `json:"id"`
	Version             int64           `json:"version"`
	VpsID               string          `json:"vps_id"`
	VpsName             sql.NullString  `json:"vps_name"`
	Provider            sql.NullString  `json:"provider"`
	InstanceType        sql.NullString  `json:"instance_type"`
	CpuCores            sql.NullInt64   `json:"cpu_cores"`
	MemoryGb            sql.NullInt64   `json:"memory_gb"`
	DiskGb              sql.NullInt64   `json:"disk_gb"`
	BandwidthMbps       sql.NullInt64   `json:"bandwidth_mbps"`
	PublicIp            sql.NullString  `json:"public_ip"`
	PrivateIp           sql.NullString  `json:"private_ip"`
	Port                sql.NullInt64   `json:"port"`
	Region              sql.NullString  `json:"region"`
	Zone                sql.NullString  `json:"zone"`
	Country             sql.NullString  `json:"country"`
	City                sql.NullString  `json:"city"`
	Latitude            sql.NullFloat64 `json:"latitude"`
	Longitude           sql.NullFloat64 `json:"longitude"`
	CpuUsage            sql.NullFloat64 `json:"cpu_usage"`
	MemoryUsage         sql.NullFloat64 `json:"memory_usage"`
	DiskUsage           sql.NullFloat64 `json:"disk_usage"`
	NetworkInMbps       sql.NullFloat64 `json:"network_in_mbps"`
	NetworkOutMbps      sql.NullFloat64 `json:"network_out_mbps"`
	LoadAverage         sql.NullFloat64 `json:"load_average"`
	UptimeHours         sql.NullInt64   `json:"uptime_hours"`
	Status              sql.NullInt64   `json:"status"`
	LastPingTime        sql.NullString  `json:"last_ping_time"`
	ResponseTimeMs      sql.NullInt64   `json:"response_time_ms"`
	IsMonitoringEnabled sql.NullInt64   `json:"is_monitoring_enabled"`
	Username            sql.NullString  `json:"username"`
	Password            sql.NullString  `json:"password"`
	SshKey              sql.NullString  `json:"ssh_key"`
	OsType              sql.NullString  `json:"os_type"`
	OsVersion           sql.NullString  `json:"os_version"`
	Architecture        sql.NullString  `json:"architecture"`
	MonthlyCost         sql.NullFloat64 `json:"monthly_cost"`
	Remark              sql.NullString  `json:"remark"`
	Tags                sql.NullString  `json:"tags"`
	CreatedAt           sql.NullString  `json:"created_at"`
	UpdatedAt           sql.NullString  `json:"updated_at"`
	LastMonitorTime     sql.NullString  `json:"last_monitor_time"`
}
