// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: multipart_upload.sql

package repo

import (
	"context"
	"database/sql"
)

const createMultipartUploadRecord = `-- name: CreateMultipartUploadRecord :exec

INSERT INTO oci_multipart_upload_record
    (tenant_id, cloud_type, tenancy_ocid, namespace, bucket_name, object_name,
     upload_id, total_size, chunk_size, total_parts, completed_parts, status,
     create_time, update_time)
VALUES (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, '[]', 'uploading', ?, ?)
`

type CreateMultipartUploadRecordParams struct {
	TenantID    int64          `json:"tenant_id"`
	TenancyOcid sql.NullString `json:"tenancy_ocid"`
	Namespace   sql.NullString `json:"namespace"`
	BucketName  string         `json:"bucket_name"`
	ObjectName  string         `json:"object_name"`
	UploadID    string         `json:"upload_id"`
	TotalSize   sql.NullInt64  `json:"total_size"`
	ChunkSize   sql.NullInt64  `json:"chunk_size"`
	TotalParts  sql.NullInt64  `json:"total_parts"`
	CreateTime  sql.NullString `json:"create_time"`
	UpdateTime  sql.NullString `json:"update_time"`
}

// Multipart upload tracking queries (Phase 11.1). Resumable upload sessions
// with per-part completion tracking via JSON column.
func (q *Queries) CreateMultipartUploadRecord(ctx context.Context, arg CreateMultipartUploadRecordParams) error {
	_, err := q.db.ExecContext(ctx, createMultipartUploadRecord,
		arg.TenantID,
		arg.TenancyOcid,
		arg.Namespace,
		arg.BucketName,
		arg.ObjectName,
		arg.UploadID,
		arg.TotalSize,
		arg.ChunkSize,
		arg.TotalParts,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const deleteMultipartUploadsByTenant = `-- name: DeleteMultipartUploadsByTenant :exec
DELETE FROM oci_multipart_upload_record WHERE tenant_id = ?
`

func (q *Queries) DeleteMultipartUploadsByTenant(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMultipartUploadsByTenant, tenantID)
	return err
}

const findActiveUploads = `-- name: FindActiveUploads :many
SELECT id, tenant_id, cloud_type, tenancy_ocid, namespace, bucket_name, object_name, upload_id, total_size, chunk_size, total_parts, completed_parts, status, create_time, update_time FROM oci_multipart_upload_record
WHERE tenant_id = ? AND bucket_name = ? AND object_name = ? AND status = 'uploading'
`

type FindActiveUploadsParams struct {
	TenantID   int64  `json:"tenant_id"`
	BucketName string `json:"bucket_name"`
	ObjectName string `json:"object_name"`
}

func (q *Queries) FindActiveUploads(ctx context.Context, arg FindActiveUploadsParams) ([]OciMultipartUploadRecord, error) {
	rows, err := q.db.QueryContext(ctx, findActiveUploads, arg.TenantID, arg.BucketName, arg.ObjectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OciMultipartUploadRecord{}
	for rows.Next() {
		var i OciMultipartUploadRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudType,
			&i.TenancyOcid,
			&i.Namespace,
			&i.BucketName,
			&i.ObjectName,
			&i.UploadID,
			&i.TotalSize,
			&i.ChunkSize,
			&i.TotalParts,
			&i.CompletedParts,
			&i.Status,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findByUploadId = `-- name: FindByUploadId :one
SELECT id, tenant_id, cloud_type, tenancy_ocid, namespace, bucket_name, object_name, upload_id, total_size, chunk_size, total_parts, completed_parts, status, create_time, update_time FROM oci_multipart_upload_record WHERE upload_id = ?
`

func (q *Queries) FindByUploadId(ctx context.Context, uploadID string) (OciMultipartUploadRecord, error) {
	row := q.db.QueryRowContext(ctx, findByUploadId, uploadID)
	var i OciMultipartUploadRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CloudType,
		&i.TenancyOcid,
		&i.Namespace,
		&i.BucketName,
		&i.ObjectName,
		&i.UploadID,
		&i.TotalSize,
		&i.ChunkSize,
		&i.TotalParts,
		&i.CompletedParts,
		&i.Status,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const findStaleUploads = `-- name: FindStaleUploads :many
SELECT id, tenant_id, cloud_type, tenancy_ocid, namespace, bucket_name, object_name, upload_id, total_size, chunk_size, total_parts, completed_parts, status, create_time, update_time FROM oci_multipart_upload_record
WHERE status = 'uploading' AND update_time < ?
`

func (q *Queries) FindStaleUploads(ctx context.Context, updateTime sql.NullString) ([]OciMultipartUploadRecord, error) {
	rows, err := q.db.QueryContext(ctx, findStaleUploads, updateTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OciMultipartUploadRecord{}
	for rows.Next() {
		var i OciMultipartUploadRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudType,
			&i.TenancyOcid,
			&i.Namespace,
			&i.BucketName,
			&i.ObjectName,
			&i.UploadID,
			&i.TotalSize,
			&i.ChunkSize,
			&i.TotalParts,
			&i.CompletedParts,
			&i.Status,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fixMultipartUploadTenantId = `-- name: FixMultipartUploadTenantId :exec
UPDATE oci_multipart_upload_record
SET tenant_id = ?, update_time = ?
WHERE tenancy_ocid = ? AND tenant_id != ?
`

type FixMultipartUploadTenantIdParams struct {
	TenantID    int64          `json:"tenant_id"`
	UpdateTime  sql.NullString `json:"update_time"`
	TenancyOcid sql.NullString `json:"tenancy_ocid"`
	TenantID_2  int64          `json:"tenant_id_2"`
}

func (q *Queries) FixMultipartUploadTenantId(ctx context.Context, arg FixMultipartUploadTenantIdParams) error {
	_, err := q.db.ExecContext(ctx, fixMultipartUploadTenantId,
		arg.TenantID,
		arg.UpdateTime,
		arg.TenancyOcid,
		arg.TenantID_2,
	)
	return err
}

const listResumableUploads = `-- name: ListResumableUploads :many
SELECT id, tenant_id, cloud_type, tenancy_ocid, namespace, bucket_name, object_name, upload_id, total_size, chunk_size, total_parts, completed_parts, status, create_time, update_time FROM oci_multipart_upload_record
WHERE tenant_id = ? AND bucket_name = ? AND status = 'uploading'
ORDER BY create_time DESC
`

type ListResumableUploadsParams struct {
	TenantID   int64  `json:"tenant_id"`
	BucketName string `json:"bucket_name"`
}

func (q *Queries) ListResumableUploads(ctx context.Context, arg ListResumableUploadsParams) ([]OciMultipartUploadRecord, error) {
	rows, err := q.db.QueryContext(ctx, listResumableUploads, arg.TenantID, arg.BucketName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OciMultipartUploadRecord{}
	for rows.Next() {
		var i OciMultipartUploadRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CloudType,
			&i.TenancyOcid,
			&i.Namespace,
			&i.BucketName,
			&i.ObjectName,
			&i.UploadID,
			&i.TotalSize,
			&i.ChunkSize,
			&i.TotalParts,
			&i.CompletedParts,
			&i.Status,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMultipartUploadParts = `-- name: UpdateMultipartUploadParts :exec
UPDATE oci_multipart_upload_record
SET completed_parts = ?, update_time = ?
WHERE upload_id = ?
`

type UpdateMultipartUploadPartsParams struct {
	CompletedParts sql.NullString `json:"completed_parts"`
	UpdateTime     sql.NullString `json:"update_time"`
	UploadID       string         `json:"upload_id"`
}

func (q *Queries) UpdateMultipartUploadParts(ctx context.Context, arg UpdateMultipartUploadPartsParams) error {
	_, err := q.db.ExecContext(ctx, updateMultipartUploadParts, arg.CompletedParts, arg.UpdateTime, arg.UploadID)
	return err
}

const updateMultipartUploadStatus = `-- name: UpdateMultipartUploadStatus :exec
UPDATE oci_multipart_upload_record
SET status = ?, update_time = ?
WHERE upload_id = ?
`

type UpdateMultipartUploadStatusParams struct {
	Status     sql.NullString `json:"status"`
	UpdateTime sql.NullString `json:"update_time"`
	UploadID   string         `json:"upload_id"`
}

func (q *Queries) UpdateMultipartUploadStatus(ctx context.Context, arg UpdateMultipartUploadStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMultipartUploadStatus, arg.Status, arg.UpdateTime, arg.UploadID)
	return err
}
