// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nginx_config.sql

package repo

import (
	"context"
	"database/sql"
)

const clearCurrentNginxConfig = `-- name: ClearCurrentNginxConfig :exec
UPDATE nginx_config SET is_current = 0, update_time = ? WHERE is_current = 1
`

func (q *Queries) ClearCurrentNginxConfig(ctx context.Context, updateTime sql.NullString) error {
	_, err := q.db.ExecContext(ctx, clearCurrentNginxConfig, updateTime)
	return err
}

const findCurrentNginxConfig = `-- name: FindCurrentNginxConfig :one
SELECT id, config_name, config_content, is_current, config_version, config_status, create_time, update_time FROM nginx_config WHERE is_current = 1 LIMIT 1
`

func (q *Queries) FindCurrentNginxConfig(ctx context.Context) (NginxConfig, error) {
	row := q.db.QueryRowContext(ctx, findCurrentNginxConfig)
	var i NginxConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigContent,
		&i.IsCurrent,
		&i.ConfigVersion,
		&i.ConfigStatus,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const findLatestNginxConfig = `-- name: FindLatestNginxConfig :one
SELECT id, config_name, config_content, is_current, config_version, config_status, create_time, update_time FROM nginx_config ORDER BY config_version DESC LIMIT 1
`

func (q *Queries) FindLatestNginxConfig(ctx context.Context) (NginxConfig, error) {
	row := q.db.QueryRowContext(ctx, findLatestNginxConfig)
	var i NginxConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigContent,
		&i.IsCurrent,
		&i.ConfigVersion,
		&i.ConfigStatus,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const findNginxConfigById = `-- name: FindNginxConfigById :one
SELECT id, config_name, config_content, is_current, config_version, config_status, create_time, update_time FROM nginx_config WHERE id = ?
`

func (q *Queries) FindNginxConfigById(ctx context.Context, id int64) (NginxConfig, error) {
	row := q.db.QueryRowContext(ctx, findNginxConfigById, id)
	var i NginxConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigName,
		&i.ConfigContent,
		&i.IsCurrent,
		&i.ConfigVersion,
		&i.ConfigStatus,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const insertNginxConfig = `-- name: InsertNginxConfig :one

INSERT INTO nginx_config (
    config_name, config_content, is_current, config_version, config_status,
    create_time, update_time
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertNginxConfigParams struct {
	ConfigName    sql.NullString `json:"config_name"`
	ConfigContent sql.NullString `json:"config_content"`
	IsCurrent     sql.NullInt64  `json:"is_current"`
	ConfigVersion sql.NullInt64  `json:"config_version"`
	ConfigStatus  sql.NullString `json:"config_status"`
	CreateTime    sql.NullString `json:"create_time"`
	UpdateTime    sql.NullString `json:"update_time"`
}

// NginxConfig queries (Phase 12.1). nginx_config stores versioned, compiled
// nginx server-block content. is_current marks the version currently applied
// to OpenResty. ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) InsertNginxConfig(ctx context.Context, arg InsertNginxConfigParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertNginxConfig,
		arg.ConfigName,
		arg.ConfigContent,
		arg.IsCurrent,
		arg.ConfigVersion,
		arg.ConfigStatus,
		arg.CreateTime,
		arg.UpdateTime,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markNginxConfigCurrent = `-- name: MarkNginxConfigCurrent :exec
UPDATE nginx_config SET is_current = 1, config_status = 'APPLIED', update_time = ? WHERE id = ?
`

type MarkNginxConfigCurrentParams struct {
	UpdateTime sql.NullString `json:"update_time"`
	ID         int64          `json:"id"`
}

func (q *Queries) MarkNginxConfigCurrent(ctx context.Context, arg MarkNginxConfigCurrentParams) error {
	_, err := q.db.ExecContext(ctx, markNginxConfigCurrent, arg.UpdateTime, arg.ID)
	return err
}
