// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxy_config.sql

package repo

import (
	"context"
	"database/sql"
)

const countProxyConfigs = `-- name: CountProxyConfigs :one
SELECT COUNT(*) FROM proxy_config
`

func (q *Queries) CountProxyConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProxyConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProxyConfig = `-- name: DeleteProxyConfig :exec
DELETE FROM proxy_config WHERE id = ?
`

func (q *Queries) DeleteProxyConfig(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProxyConfig, id)
	return err
}

const existsProxyConfigByDomain = `-- name: ExistsProxyConfigByDomain :one
SELECT COUNT(*) FROM proxy_config WHERE domain = ?
`

func (q *Queries) ExistsProxyConfigByDomain(ctx context.Context, domain string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsProxyConfigByDomain, domain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findProxyConfigById = `-- name: FindProxyConfigById :one
SELECT id, domain, target_host, target_port, protocol, enable_ssl, enable_websocket, ssl_certificate_id, config_status, ssl_status, custom_config, remark, load_balance_type, enable_health_check, health_check_path, health_check_interval, enable_rate_limit, rate_limit, enable_cache, cache_time, create_time, update_time FROM proxy_config WHERE id = ?
`

func (q *Queries) FindProxyConfigById(ctx context.Context, id int64) (ProxyConfig, error) {
	row := q.db.QueryRowContext(ctx, findProxyConfigById, id)
	var i ProxyConfig
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.TargetHost,
		&i.TargetPort,
		&i.Protocol,
		&i.EnableSsl,
		&i.EnableWebsocket,
		&i.SslCertificateID,
		&i.ConfigStatus,
		&i.SslStatus,
		&i.CustomConfig,
		&i.Remark,
		&i.LoadBalanceType,
		&i.EnableHealthCheck,
		&i.HealthCheckPath,
		&i.HealthCheckInterval,
		&i.EnableRateLimit,
		&i.RateLimit,
		&i.EnableCache,
		&i.CacheTime,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const findProxyConfigsBySslCertId = `-- name: FindProxyConfigsBySslCertId :many
SELECT id, domain, target_host, target_port, protocol, enable_ssl, enable_websocket, ssl_certificate_id, config_status, ssl_status, custom_config, remark, load_balance_type, enable_health_check, health_check_path, health_check_interval, enable_rate_limit, rate_limit, enable_cache, cache_time, create_time, update_time FROM proxy_config WHERE ssl_certificate_id = ?
`

func (q *Queries) FindProxyConfigsBySslCertId(ctx context.Context, sslCertificateID sql.NullInt64) ([]ProxyConfig, error) {
	rows, err := q.db.QueryContext(ctx, findProxyConfigsBySslCertId, sslCertificateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyConfig{}
	for rows.Next() {
		var i ProxyConfig
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.TargetHost,
			&i.TargetPort,
			&i.Protocol,
			&i.EnableSsl,
			&i.EnableWebsocket,
			&i.SslCertificateID,
			&i.ConfigStatus,
			&i.SslStatus,
			&i.CustomConfig,
			&i.Remark,
			&i.LoadBalanceType,
			&i.EnableHealthCheck,
			&i.HealthCheckPath,
			&i.HealthCheckInterval,
			&i.EnableRateLimit,
			&i.RateLimit,
			&i.EnableCache,
			&i.CacheTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProxyConfig = `-- name: InsertProxyConfig :exec

INSERT INTO proxy_config (
    domain, target_host, target_port, protocol, enable_ssl, enable_websocket,
    ssl_certificate_id, config_status, ssl_status, custom_config, remark,
    load_balance_type, enable_health_check, health_check_path, health_check_interval,
    enable_rate_limit, rate_limit, enable_cache, cache_time, create_time, update_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertProxyConfigParams struct {
	Domain              string         `json:"domain"`
	TargetHost          string         `json:"target_host"`
	TargetPort          int64          `json:"target_port"`
	Protocol            sql.NullString `json:"protocol"`
	EnableSsl           sql.NullInt64  `json:"enable_ssl"`
	EnableWebsocket     sql.NullInt64  `json:"enable_websocket"`
	SslCertificateID    sql.NullInt64  `json:"ssl_certificate_id"`
	ConfigStatus        sql.NullString `json:"config_status"`
	SslStatus           sql.NullString `json:"ssl_status"`
	CustomConfig        sql.NullString `json:"custom_config"`
	Remark              sql.NullString `json:"remark"`
	LoadBalanceType     sql.NullString `json:"load_balance_type"`
	EnableHealthCheck   sql.NullInt64  `json:"enable_health_check"`
	HealthCheckPath     sql.NullString `json:"health_check_path"`
	HealthCheckInterval sql.NullInt64  `json:"health_check_interval"`
	EnableRateLimit     sql.NullInt64  `json:"enable_rate_limit"`
	RateLimit           sql.NullInt64  `json:"rate_limit"`
	EnableCache         sql.NullInt64  `json:"enable_cache"`
	CacheTime           sql.NullInt64  `json:"cache_time"`
	CreateTime          sql.NullString `json:"create_time"`
	UpdateTime          sql.NullString `json:"update_time"`
}

// ProxyConfig queries (Phase 12.1). proxy_config stores per-domain reverse
// proxy rules with target host/port, SSL, WebSocket, rate limiting, caching,
// and custom config blocks. ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) InsertProxyConfig(ctx context.Context, arg InsertProxyConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertProxyConfig,
		arg.Domain,
		arg.TargetHost,
		arg.TargetPort,
		arg.Protocol,
		arg.EnableSsl,
		arg.EnableWebsocket,
		arg.SslCertificateID,
		arg.ConfigStatus,
		arg.SslStatus,
		arg.CustomConfig,
		arg.Remark,
		arg.LoadBalanceType,
		arg.EnableHealthCheck,
		arg.HealthCheckPath,
		arg.HealthCheckInterval,
		arg.EnableRateLimit,
		arg.RateLimit,
		arg.EnableCache,
		arg.CacheTime,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const listActiveProxyConfigs = `-- name: ListActiveProxyConfigs :many
SELECT id, domain, target_host, target_port, protocol, enable_ssl, enable_websocket, ssl_certificate_id, config_status, ssl_status, custom_config, remark, load_balance_type, enable_health_check, health_check_path, health_check_interval, enable_rate_limit, rate_limit, enable_cache, cache_time, create_time, update_time FROM proxy_config WHERE config_status != 'DISABLED' ORDER BY create_time DESC
`

func (q *Queries) ListActiveProxyConfigs(ctx context.Context) ([]ProxyConfig, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProxyConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyConfig{}
	for rows.Next() {
		var i ProxyConfig
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.TargetHost,
			&i.TargetPort,
			&i.Protocol,
			&i.EnableSsl,
			&i.EnableWebsocket,
			&i.SslCertificateID,
			&i.ConfigStatus,
			&i.SslStatus,
			&i.CustomConfig,
			&i.Remark,
			&i.LoadBalanceType,
			&i.EnableHealthCheck,
			&i.HealthCheckPath,
			&i.HealthCheckInterval,
			&i.EnableRateLimit,
			&i.RateLimit,
			&i.EnableCache,
			&i.CacheTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProxyConfigs = `-- name: ListProxyConfigs :many
SELECT id, domain, target_host, target_port, protocol, enable_ssl, enable_websocket, ssl_certificate_id, config_status, ssl_status, custom_config, remark, load_balance_type, enable_health_check, health_check_path, health_check_interval, enable_rate_limit, rate_limit, enable_cache, cache_time, create_time, update_time FROM proxy_config ORDER BY create_time DESC LIMIT ? OFFSET ?
`

type ListProxyConfigsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProxyConfigs(ctx context.Context, arg ListProxyConfigsParams) ([]ProxyConfig, error) {
	rows, err := q.db.QueryContext(ctx, listProxyConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyConfig{}
	for rows.Next() {
		var i ProxyConfig
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.TargetHost,
			&i.TargetPort,
			&i.Protocol,
			&i.EnableSsl,
			&i.EnableWebsocket,
			&i.SslCertificateID,
			&i.ConfigStatus,
			&i.SslStatus,
			&i.CustomConfig,
			&i.Remark,
			&i.LoadBalanceType,
			&i.EnableHealthCheck,
			&i.HealthCheckPath,
			&i.HealthCheckInterval,
			&i.EnableRateLimit,
			&i.RateLimit,
			&i.EnableCache,
			&i.CacheTime,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxyConfig = `-- name: UpdateProxyConfig :exec
UPDATE proxy_config
SET domain = ?, target_host = ?, target_port = ?, protocol = ?, enable_ssl = ?,
    enable_websocket = ?, ssl_certificate_id = ?, config_status = ?, ssl_status = ?,
    custom_config = ?, remark = ?, load_balance_type = ?, enable_health_check = ?,
    health_check_path = ?, health_check_interval = ?, enable_rate_limit = ?,
    rate_limit = ?, enable_cache = ?, cache_time = ?, update_time = ?
WHERE id = ?
`

type UpdateProxyConfigParams struct {
	Domain              string         `json:"domain"`
	TargetHost          string         `json:"target_host"`
	TargetPort          int64          `json:"target_port"`
	Protocol            sql.NullString `json:"protocol"`
	EnableSsl           sql.NullInt64  `json:"enable_ssl"`
	EnableWebsocket     sql.NullInt64  `json:"enable_websocket"`
	SslCertificateID    sql.NullInt64  `json:"ssl_certificate_id"`
	ConfigStatus        sql.NullString `json:"config_status"`
	SslStatus           sql.NullString `json:"ssl_status"`
	CustomConfig        sql.NullString `json:"custom_config"`
	Remark              sql.NullString `json:"remark"`
	LoadBalanceType     sql.NullString `json:"load_balance_type"`
	EnableHealthCheck   sql.NullInt64  `json:"enable_health_check"`
	HealthCheckPath     sql.NullString `json:"health_check_path"`
	HealthCheckInterval sql.NullInt64  `json:"health_check_interval"`
	EnableRateLimit     sql.NullInt64  `json:"enable_rate_limit"`
	RateLimit           sql.NullInt64  `json:"rate_limit"`
	EnableCache         sql.NullInt64  `json:"enable_cache"`
	CacheTime           sql.NullInt64  `json:"cache_time"`
	UpdateTime          sql.NullString `json:"update_time"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateProxyConfig(ctx context.Context, arg UpdateProxyConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateProxyConfig,
		arg.Domain,
		arg.TargetHost,
		arg.TargetPort,
		arg.Protocol,
		arg.EnableSsl,
		arg.EnableWebsocket,
		arg.SslCertificateID,
		arg.ConfigStatus,
		arg.SslStatus,
		arg.CustomConfig,
		arg.Remark,
		arg.LoadBalanceType,
		arg.EnableHealthCheck,
		arg.HealthCheckPath,
		arg.HealthCheckInterval,
		arg.EnableRateLimit,
		arg.RateLimit,
		arg.EnableCache,
		arg.CacheTime,
		arg.UpdateTime,
		arg.ID,
	)
	return err
}

const updateProxyConfigSslFields = `-- name: UpdateProxyConfigSslFields :exec
UPDATE proxy_config SET ssl_certificate_id = ?, enable_ssl = ?, ssl_status = ?, update_time = ? WHERE id = ?
`

type UpdateProxyConfigSslFieldsParams struct {
	SslCertificateID sql.NullInt64  `json:"ssl_certificate_id"`
	EnableSsl        sql.NullInt64  `json:"enable_ssl"`
	SslStatus        sql.NullString `json:"ssl_status"`
	UpdateTime       sql.NullString `json:"update_time"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateProxyConfigSslFields(ctx context.Context, arg UpdateProxyConfigSslFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateProxyConfigSslFields,
		arg.SslCertificateID,
		arg.EnableSsl,
		arg.SslStatus,
		arg.UpdateTime,
		arg.ID,
	)
	return err
}

const updateProxyConfigStatus = `-- name: UpdateProxyConfigStatus :exec
UPDATE proxy_config SET config_status = ?, update_time = ? WHERE id = ?
`

type UpdateProxyConfigStatusParams struct {
	ConfigStatus sql.NullString `json:"config_status"`
	UpdateTime   sql.NullString `json:"update_time"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateProxyConfigStatus(ctx context.Context, arg UpdateProxyConfigStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateProxyConfigStatus, arg.ConfigStatus, arg.UpdateTime, arg.ID)
	return err
}
