// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdvanceNextExecutionTime(ctx context.Context, arg AdvanceNextExecutionTimeParams) error
	CountAppVersion(ctx context.Context) (int64, error)
	CountBootInstancesByTenantId(ctx context.Context, tenantID sql.NullInt64) (int64, error)
	CountByLoginType(ctx context.Context, loginType string) (int64, error)
	CountEmailBodies(ctx context.Context, nullif interface{}) (int64, error)
	CountEmailReceives(ctx context.Context, arg CountEmailReceivesParams) (int64, error)
	CountEmailSendRecords(ctx context.Context, emailBodyID sql.NullString) (int64, error)
	CountInstanceDetails(ctx context.Context) (int64, error)
	CountRunningTasks(ctx context.Context) (int64, error)
	CountTenantChildren(ctx context.Context, parenID sql.NullInt64) (int64, error)
	CountTenantEmailConfigs(ctx context.Context) (int64, error)
	CountTotalTasks(ctx context.Context) (int64, error)
	// Multipart upload tracking queries (Phase 11.1). Resumable upload sessions
	// with per-part completion tracking via JSON column.
	CreateMultipartUploadRecord(ctx context.Context, arg CreateMultipartUploadRecordParams) error
	DeleteComputerInfo(ctx context.Context, bootIDStr sql.NullString) error
	DeleteEmailBodiesByConfigId(ctx context.Context, tenantEmailConfigID sql.NullInt64) error
	DeleteEmailBody(ctx context.Context, emailBodyID string) error
	DeleteEmailReceive(ctx context.Context, id int64) error
	DeleteEmailSendRecordsByBodyId(ctx context.Context, emailBodyID sql.NullString) error
	DeleteEmailSendRecordsByConfigId(ctx context.Context, tenantEmailConfigID sql.NullInt64) error
	DeleteImageCacheByTenant(ctx context.Context, tenantID int64) error
	DeleteInstanceBackupDetail(ctx context.Context, id int64) error
	DeleteInstanceDetail(ctx context.Context, id int64) error
	// instance_detail queries (Phase 3 instance sync). Sync is delete-by-tenant
	// then insert-all (parity with Java syncOci: deleteByTenantId then saveAll).
	DeleteInstanceDetailsByTenantId(ctx context.Context, tenantID sql.NullInt64) error
	DeleteInstanceTrafficByTenantId(ctx context.Context, tenantID sql.NullInt64) error
	DeleteLock(ctx context.Context, taskID string) error
	DeleteMultipartUploadsByTenant(ctx context.Context, tenantID int64) error
	DeleteProcessingLocks(ctx context.Context) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSessionsByUsername(ctx context.Context, username string) error
	DeleteShapeCacheByTenant(ctx context.Context, tenantID int64) error
	DeleteTemInstancesByTenancy(ctx context.Context, tenancy sql.NullString) error
	DeleteTenant(ctx context.Context, id int64) error
	DeleteTenantEmailConfig(ctx context.Context, tenantID sql.NullInt64) error
	DeleteTenantSocial(ctx context.Context, id int64) error
	DeleteVpnProxyRecord(ctx context.Context, id int64) error
	DisableBootInstance(ctx context.Context, arg DisableBootInstanceParams) error
	EnableBootInstance(ctx context.Context, arg EnableBootInstanceParams) error
	ExistsByUsername(ctx context.Context, username string) (int64, error)
	FindActiveUploads(ctx context.Context, arg FindActiveUploadsParams) ([]OciMultipartUploadRecord, error)
	FindBootInstanceByBootID(ctx context.Context, bootID sql.NullString) (BootInstance, error)
	FindBootInstanceByID(ctx context.Context, id int64) (BootInstance, error)
	FindByUploadId(ctx context.Context, uploadID string) (OciMultipartUploadRecord, error)
	// Cloud tenancy queries (Phase 9). cloud_tenancy stores account cost and
	// custom name per tenancy.
	FindCloudTenancyByName(ctx context.Context, tenancyName string) (CloudTenancy, error)
	// Replaces the inline compartment_id lookup in wsHub.Console.SetDeps
	// GetCompartmentID.
	FindCompartmentID(ctx context.Context, instanceID sql.NullString) (sql.NullString, error)
	// oci_computer_info queries
	FindComputerInfoByBootIDStr(ctx context.Context, bootIDStr sql.NullString) (OciComputerInfo, error)
	// system_config is the runtime KV store (config_key UNIQUE).
	// Boolean configs use the config_enabled column (INTEGER 0/1);
	// string configs use config_value. Mirrors Java SystemConfigService.
	FindConfigByKey(ctx context.Context, configKey sql.NullString) (SystemConfig, error)
	// Replaces the inline SELECT in cmd/oci-start/main.go wsHub.Console.SetDeps.
	// Returns the columns the console closure scans: instance_id, display_name,
	// public_ips, private_ips, shape, username, port, password, tenant_id,
	// compartment_id, availability_domain.
	FindConsoleInstanceInfo(ctx context.Context, instanceID sql.NullString) (FindConsoleInstanceInfoRow, error)
	// Grabber queries (Phase 4). boot_instance, open_boot_lock, oci_computer_info,
	// tem_instance. See SPEC S8; parity with BootInstanceRepository +
	// OpenBootLockRepository + BootTotalInstanceService queries.
	// ALL COMMENTS MUST BE ASCII-ONLY (sqlc v1.31.1 sqlite parser corrupts queries
	// when a -- comment contains non-ASCII characters).
	FindDistinctTasksToExecute(ctx context.Context, arg FindDistinctTasksToExecuteParams) ([]FindDistinctTasksToExecuteRow, error)
	FindEmailBodyById(ctx context.Context, emailBodyID string) (EmailBody, error)
	// Email receive (recipient) queries (Phase 12.2). email_receive stores
	// email recipients for batch sending.
	// ALL COMMENTS MUST BE ASCII-ONLY.
	FindEmailReceiveById(ctx context.Context, id int64) (EmailReceive, error)
	// instance_backup_detail queries
	FindInstanceBackupsByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]InstanceBackupDetail, error)
	// Extended instance_detail queries (Phase 5). Instance management, traffic,
	// backup records. ALL COMMENTS MUST BE ASCII-ONLY.
	FindInstanceDetailByID(ctx context.Context, id int64) (FindInstanceDetailByIDRow, error)
	// instance_traffic queries
	FindInstanceTrafficByInstanceId(ctx context.Context, arg FindInstanceTrafficByInstanceIdParams) ([]InstanceTraffic, error)
	FindInstancesByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]FindInstancesByTenantIdRow, error)
	// open_boot_lock queries
	FindLockByTaskID(ctx context.Context, taskID string) (OpenBootLock, error)
	FindOfflineInstances(ctx context.Context, lastHeartbeat sql.NullString) ([]FindOfflineInstancesRow, error)
	// VpnProxyRecord queries (Phase 3 SOCKS proxy pool). Random available pick
	// parity with VpnProxyRecordRepository.findRandomAvailableRecord.
	FindRandomAvailableProxy(ctx context.Context) (VpnProxyRecord, error)
	// RegisterDetail queries (Phase 9). register_detail stores OCI subscription
	// information including register_time (timeStart) used for active-days calculation.
	// ALL COMMENTS MUST BE ASCII-ONLY.
	FindRegisterDetailByTenantId(ctx context.Context, tenantID sql.NullString) (FindRegisterDetailByTenantIdRow, error)
	// Replaces the inline SELECT in cmd/oci-start/main.go wsHub.Rescue.SetDeps.
	// Returns: instance_id, display_name, state, boot_volume_id, shape,
	// availability_domain, compartment_id, public_ips, username, password.
	FindRescueInstanceInfo(ctx context.Context, instanceID sql.NullString) (FindRescueInstanceInfoRow, error)
	FindSessionByToken(ctx context.Context, token string) (LoginSession, error)
	FindStaleUploads(ctx context.Context, updateTime sql.NullString) ([]OciMultipartUploadRecord, error)
	FindTenantByID(ctx context.Context, id int64) (Tenant, error)
	// Extended tenant email config queries (Phase 12.2). OCI provisioning fields,
	// daily send tracking, and admin list endpoint.
	// ALL COMMENTS MUST BE ASCII-ONLY.
	FindTenantEmailConfigById(ctx context.Context, id int64) (TenantEmailConfig, error)
	// Tenant email config queries (Phase 9). tenant_email_config stores SES/SMTP
	// configuration per tenant for email service.
	FindTenantEmailConfigByTenantId(ctx context.Context, tenantID sql.NullInt64) (TenantEmailConfig, error)
	FindTenantFullByID(ctx context.Context, id int64) (FindTenantFullByIDRow, error)
	FindTenantSocialByType(ctx context.Context, arg FindTenantSocialByTypeParams) (TenantSocial, error)
	FindTenantsByParenId(ctx context.Context, parenID sql.NullInt64) ([]FindTenantsByParenIdRow, error)
	FindTopBanByIpAddress(ctx context.Context, ipAddress string) (BanRecord, error)
	// traffic_alert queries
	FindTrafficAlertByTenantId(ctx context.Context, tenantID int64) (TrafficAlert, error)
	FindUserByExternalIdAndLoginType(ctx context.Context, arg FindUserByExternalIdAndLoginTypeParams) (LoginUser, error)
	FindUserByUsername(ctx context.Context, username string) (LoginUser, error)
	FixMultipartUploadTenantId(ctx context.Context, arg FixMultipartUploadTenantIdParams) error
	GetAppVersion(ctx context.Context) (AppVersion, error)
	IncrementFailCount(ctx context.Context, id int64) error
	IncrementSuccessCount(ctx context.Context, arg IncrementSuccessCountParams) error
	InsertBan(ctx context.Context, arg InsertBanParams) error
	InsertBootInstance(ctx context.Context, arg InsertBootInstanceParams) error
	InsertComputerInfo(ctx context.Context, arg InsertComputerInfoParams) error
	// Email body (batch) queries (Phase 12.2). email_body tracks email batch
	// send operations with aggregated success/fail counts.
	// ALL COMMENTS MUST BE ASCII-ONLY.
	InsertEmailBody(ctx context.Context, arg InsertEmailBodyParams) error
	InsertEmailReceive(ctx context.Context, arg InsertEmailReceiveParams) error
	// Email send record queries (Phase 12.2). email_send_record tracks per-recipient
	// send results for each email body batch.
	// ALL COMMENTS MUST BE ASCII-ONLY.
	InsertEmailSendRecord(ctx context.Context, arg InsertEmailSendRecordParams) error
	InsertInstanceBackupDetail(ctx context.Context, arg InsertInstanceBackupDetailParams) error
	InsertInstanceDetail(ctx context.Context, arg InsertInstanceDetailParams) error
	InsertInstanceTraffic(ctx context.Context, arg InsertInstanceTrafficParams) error
	InsertLockIgnore(ctx context.Context, arg InsertLockIgnoreParams) error
	InsertLoginUser(ctx context.Context, arg InsertLoginUserParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	// tem_instance queries (temp instance tracking during grab)
	InsertTemInstance(ctx context.Context, arg InsertTemInstanceParams) error
	InsertTenant(ctx context.Context, arg InsertTenantParams) error
	InsertTenantSocial(ctx context.Context, arg InsertTenantSocialParams) error
	InsertVpnProxyRecord(ctx context.Context, arg InsertVpnProxyRecordParams) error
	ListAllInstanceDetails(ctx context.Context, arg ListAllInstanceDetailsParams) ([]ListAllInstanceDetailsRow, error)
	ListBootInstances(ctx context.Context) ([]BootInstance, error)
	ListEmailBodies(ctx context.Context, arg ListEmailBodiesParams) ([]EmailBody, error)
	ListEmailReceives(ctx context.Context, arg ListEmailReceivesParams) ([]EmailReceive, error)
	ListEmailSendRecords(ctx context.Context, arg ListEmailSendRecordsParams) ([]EmailSendRecord, error)
	ListImageCacheByTenant(ctx context.Context, tenantID int64) ([]ImageCache, error)
	ListImageCacheByTenantAndArch(ctx context.Context, arg ListImageCacheByTenantAndArchParams) ([]ImageCache, error)
	ListImageCacheByTenantAndOS(ctx context.Context, arg ListImageCacheByTenantAndOSParams) ([]ImageCache, error)
	ListInstanceDetailsByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]ListInstanceDetailsByTenantIdRow, error)
	ListResumableUploads(ctx context.Context, arg ListResumableUploadsParams) ([]OciMultipartUploadRecord, error)
	ListShapeCacheByTenant(ctx context.Context, tenantID int64) ([]ShapeCache, error)
	ListShapeCacheByTenantAndArch(ctx context.Context, arg ListShapeCacheByTenantAndArchParams) ([]ShapeCache, error)
	ListTenantEmailConfigs(ctx context.Context, arg ListTenantEmailConfigsParams) ([]ListTenantEmailConfigsRow, error)
	// Tenant social config queries (Phase 9). tenant_social stores third-party OAuth
	// configuration per tenant (Google, GitHub, Microsoft, etc.).
	ListTenantSocialByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]TenantSocial, error)
	// Tenant queries (Phase 3). key_file_blob holds the AES-256-GCM encrypted
	// PEM (base64). List/mask queries deliberately omit key_file/key_file_blob.
	ListTenants(ctx context.Context) ([]ListTenantsRow, error)
	// Aggregates tenant + register_detail.register_time + boot_instance count
	// (status=1) + child count in a single round-trip, replacing the per-tenant
	// FindRegisterDetailByTenantId / CountBootInstancesByTenantId / CountTenantChildren
	// fan-out in service.TenantService.List. All three enrichments are correlated
	// subqueries: this avoids the row-multiplication a LEFT JOIN would introduce
	// when register_detail has duplicate tenant_id rows (UpsertRegisterDetail uses
	// INSERT OR REPLACE with no unique constraint), and matches the first-row
	// semantics of FindRegisterDetailByTenantId (:one).
	// ALL COMMENTS MUST BE ASCII-ONLY.
	ListTenantsWithCounts(ctx context.Context) ([]ListTenantsWithCountsRow, error)
	ListTrafficAlerts(ctx context.Context) ([]TrafficAlert, error)
	ListVpnProxyRecords(ctx context.Context) ([]VpnProxyRecord, error)
	MarkDailyReset(ctx context.Context, lastResetDate sql.NullString) error
	MarkNotificationAsSent(ctx context.Context, id int64) error
	ResetDailyCounts(ctx context.Context, lastResetDate sql.NullString) error
	SeedAppVersion(ctx context.Context, arg SeedAppVersionParams) error
	SetTenantApiSynced(ctx context.Context, arg SetTenantApiSyncedParams) error
	TouchSessionActive(ctx context.Context, arg TouchSessionActiveParams) error
	UpdateAppVersion(ctx context.Context, arg UpdateAppVersionParams) error
	UpdateBanStatus(ctx context.Context, arg UpdateBanStatusParams) error
	UpdateBootInstance(ctx context.Context, arg UpdateBootInstanceParams) error
	UpdateBootInstanceStatus(ctx context.Context, arg UpdateBootInstanceStatusParams) error
	UpdateCloudTenancyCost(ctx context.Context, arg UpdateCloudTenancyCostParams) error
	UpdateComputerInfo(ctx context.Context, arg UpdateComputerInfoParams) error
	UpdateEmailBodyTotals(ctx context.Context, arg UpdateEmailBodyTotalsParams) error
	UpdateEmailSendRecordState(ctx context.Context, arg UpdateEmailSendRecordStateParams) error
	UpdateInstanceConnTime(ctx context.Context, arg UpdateInstanceConnTimeParams) error
	UpdateInstanceDetailBootVolumeSize(ctx context.Context, arg UpdateInstanceDetailBootVolumeSizeParams) error
	UpdateInstanceDetailIpv6(ctx context.Context, arg UpdateInstanceDetailIpv6Params) error
	UpdateInstanceDetailPublicIp(ctx context.Context, arg UpdateInstanceDetailPublicIpParams) error
	UpdateInstanceDetailRemark(ctx context.Context, arg UpdateInstanceDetailRemarkParams) error
	UpdateInstanceDetailVpusPerGb(ctx context.Context, arg UpdateInstanceDetailVpusPerGbParams) error
	UpdateInstanceOffline(ctx context.Context, arg UpdateInstanceOfflineParams) error
	UpdateInstanceResumeNotify(ctx context.Context, id int64) error
	UpdateInstanceSSHConfig(ctx context.Context, arg UpdateInstanceSSHConfigParams) error
	UpdateLastLoginAt(ctx context.Context, arg UpdateLastLoginAtParams) error
	UpdateLockSuccess(ctx context.Context, arg UpdateLockSuccessParams) error
	UpdateMultipartUploadParts(ctx context.Context, arg UpdateMultipartUploadPartsParams) error
	UpdateMultipartUploadStatus(ctx context.Context, arg UpdateMultipartUploadStatusParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	UpdateTenantEmailActive(ctx context.Context, arg UpdateTenantEmailActiveParams) error
	UpdateTenantEmailSentCount(ctx context.Context, arg UpdateTenantEmailSentCountParams) error
	UpdateTenantEnableFlags(ctx context.Context, arg UpdateTenantEnableFlagsParams) error
	// Extended tenant queries (Phase 9). Tenant detail, custom name, active days.
	// ALL COMMENTS MUST BE ASCII-ONLY.
	UpdateTenantFields(ctx context.Context, arg UpdateTenantFieldsParams) error
	UpdateTenantSocial(ctx context.Context, arg UpdateTenantSocialParams) error
	UpdateTenantSocialStatus(ctx context.Context, arg UpdateTenantSocialStatusParams) error
	UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error
	UpdateVpnProxyRecord(ctx context.Context, arg UpdateVpnProxyRecordParams) error
	UpsertCloudTenancy(ctx context.Context, arg UpsertCloudTenancyParams) error
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) error
	UpsertConfigEnabled(ctx context.Context, arg UpsertConfigEnabledParams) error
	UpsertConfigValue(ctx context.Context, arg UpsertConfigValueParams) error
	UpsertImageCache(ctx context.Context, arg UpsertImageCacheParams) error
	UpsertRegisterDetail(ctx context.Context, arg UpsertRegisterDetailParams) error
	UpsertShapeCache(ctx context.Context, arg UpsertShapeCacheParams) error
	UpsertTenantEmailConfig(ctx context.Context, arg UpsertTenantEmailConfigParams) error
	UpsertTenantEmailConfigFull(ctx context.Context, arg UpsertTenantEmailConfigFullParams) error
	UpsertTrafficAlert(ctx context.Context, arg UpsertTrafficAlertParams) error
}

var _ Querier = (*Queries)(nil)
