// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAppVersion(ctx context.Context) (int64, error)
	CountByLoginType(ctx context.Context, loginType string) (int64, error)
	// instance_detail queries (Phase 3 instance sync). Sync is delete-by-tenant
	// then insert-all (parity with Java syncOci: deleteByTenantId then saveAll).
	DeleteInstanceDetailsByTenantId(ctx context.Context, tenantID sql.NullInt64) error
	DeleteSession(ctx context.Context, token string) error
	DeleteSessionsByUsername(ctx context.Context, username string) error
	DeleteTenant(ctx context.Context, id int64) error
	DeleteVpnProxyRecord(ctx context.Context, id int64) error
	ExistsByUsername(ctx context.Context, username string) (int64, error)
	// system_config is the runtime KV store (config_key UNIQUE).
	// Boolean configs use the config_enabled column (INTEGER 0/1);
	// string configs use config_value. Mirrors Java SystemConfigService.
	FindConfigByKey(ctx context.Context, configKey sql.NullString) (SystemConfig, error)
	// VpnProxyRecord queries (Phase 3 SOCKS proxy pool). Random available pick
	// parity with VpnProxyRecordRepository.findRandomAvailableRecord.
	FindRandomAvailableProxy(ctx context.Context) (VpnProxyRecord, error)
	FindSessionByToken(ctx context.Context, token string) (LoginSession, error)
	FindTenantByID(ctx context.Context, id int64) (Tenant, error)
	FindTenantsByParenId(ctx context.Context, parenID sql.NullInt64) ([]FindTenantsByParenIdRow, error)
	FindTopBanByIpAddress(ctx context.Context, ipAddress string) (BanRecord, error)
	FindUserByExternalIdAndLoginType(ctx context.Context, arg FindUserByExternalIdAndLoginTypeParams) (LoginUser, error)
	FindUserByUsername(ctx context.Context, username string) (LoginUser, error)
	GetAppVersion(ctx context.Context) (AppVersion, error)
	InsertBan(ctx context.Context, arg InsertBanParams) error
	InsertInstanceDetail(ctx context.Context, arg InsertInstanceDetailParams) error
	InsertLoginUser(ctx context.Context, arg InsertLoginUserParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertTenant(ctx context.Context, arg InsertTenantParams) error
	InsertVpnProxyRecord(ctx context.Context, arg InsertVpnProxyRecordParams) error
	ListInstanceDetailsByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]ListInstanceDetailsByTenantIdRow, error)
	// Tenant queries (Phase 3). key_file_blob holds the AES-256-GCM encrypted
	// PEM (base64). List/mask queries deliberately omit key_file/key_file_blob.
	ListTenants(ctx context.Context) ([]ListTenantsRow, error)
	ListVpnProxyRecords(ctx context.Context) ([]VpnProxyRecord, error)
	SeedAppVersion(ctx context.Context, arg SeedAppVersionParams) error
	SetTenantApiSynced(ctx context.Context, arg SetTenantApiSyncedParams) error
	TouchSessionActive(ctx context.Context, arg TouchSessionActiveParams) error
	UpdateAppVersion(ctx context.Context, arg UpdateAppVersionParams) error
	UpdateBanStatus(ctx context.Context, arg UpdateBanStatusParams) error
	UpdateLastLoginAt(ctx context.Context, arg UpdateLastLoginAtParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error
	UpdateVpnProxyRecord(ctx context.Context, arg UpdateVpnProxyRecordParams) error
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) error
	UpsertConfigEnabled(ctx context.Context, arg UpsertConfigEnabledParams) error
	UpsertConfigValue(ctx context.Context, arg UpsertConfigValueParams) error
}

var _ Querier = (*Queries)(nil)
