// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register_detail.sql

package repo

import (
	"context"
	"database/sql"
)

const findRegisterDetailByTenantId = `-- name: FindRegisterDetailByTenantId :one
SELECT id, tenant_prv_id, tenant_id, account_type, plan_type, register_time,
       city, country, email_address, first_name, last_name, line1, postal_code,
       subscription_plan_number, upgrade_state, created_time, updated_time, cloud_type
FROM register_detail
WHERE tenant_id = ?
`

func (q *Queries) FindRegisterDetailByTenantId(ctx context.Context, tenantID string) (RegisterDetail, error) {
	row := q.db.QueryRowContext(ctx, findRegisterDetailByTenantId, tenantID)
	var i RegisterDetail
	err := row.Scan(
		&i.ID,
		&i.TenantPrvID,
		&i.TenantID,
		&i.AccountType,
		&i.PlanType,
		&i.RegisterTime,
		&i.City,
		&i.Country,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.Line1,
		&i.PostalCode,
		&i.SubscriptionPlanNumber,
		&i.UpgradeState,
		&i.CreatedTime,
		&i.UpdatedTime,
		&i.CloudType,
	)
	return i, err
}

const upsertRegisterDetail = `-- name: UpsertRegisterDetail :exec
INSERT OR REPLACE INTO register_detail (
    tenant_prv_id, tenant_id, account_type, plan_type, register_time,
    city, country, email_address, first_name, last_name, line1, postal_code,
    subscription_plan_number, upgrade_state, created_time, updated_time, cloud_type
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertRegisterDetailParams struct {
	TenantPrvID             sql.NullInt64  `json:"tenant_prv_id"`
	TenantID                string         `json:"tenant_id"`
	AccountType             sql.NullInt64  `json:"account_type"`
	PlanType                sql.NullInt64  `json:"plan_type"`
	RegisterTime            sql.NullString `json:"register_time"`
	City                    sql.NullString `json:"city"`
	Country                 sql.NullString `json:"country"`
	EmailAddress            sql.NullString `json:"email_address"`
	FirstName               sql.NullString `json:"first_name"`
	LastName                sql.NullString `json:"last_name"`
	Line1                   sql.NullString `json:"line1"`
	PostalCode              sql.NullString `json:"postal_code"`
	SubscriptionPlanNumber  sql.NullString `json:"subscription_plan_number"`
	UpgradeState            sql.NullString `json:"upgrade_state"`
	CreatedTime             sql.NullString `json:"created_time"`
	UpdatedTime             sql.NullString `json:"updated_time"`
	CloudType               sql.NullInt64  `json:"cloud_type"`
}

func (q *Queries) UpsertRegisterDetail(ctx context.Context, arg UpsertRegisterDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertRegisterDetail,
		arg.TenantPrvID,
		arg.TenantID,
		arg.AccountType,
		arg.PlanType,
		arg.RegisterTime,
		arg.City,
		arg.Country,
		arg.EmailAddress,
		arg.FirstName,
		arg.LastName,
		arg.Line1,
		arg.PostalCode,
		arg.SubscriptionPlanNumber,
		arg.UpgradeState,
		arg.CreatedTime,
		arg.UpdatedTime,
		arg.CloudType,
	)
	return err
}
