// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM login_session WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsByUsername = `-- name: DeleteSessionsByUsername :exec
DELETE FROM login_session WHERE username = ?
`

func (q *Queries) DeleteSessionsByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUsername, username)
	return err
}

const findSessionByToken = `-- name: FindSessionByToken :one
SELECT token, username, ip, user_agent, created_at, expires_at, last_active_at
FROM login_session
WHERE token = ?
`

func (q *Queries) FindSessionByToken(ctx context.Context, token string) (LoginSession, error) {
	row := q.db.QueryRowContext(ctx, findSessionByToken, token)
	var i LoginSession
	err := row.Scan(
		&i.Token,
		&i.Username,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActiveAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO login_session (token, username, ip, user_agent, created_at, expires_at, last_active_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	Token        string         `json:"token"`
	Username     string         `json:"username"`
	Ip           sql.NullString `json:"ip"`
	UserAgent    sql.NullString `json:"user_agent"`
	CreatedAt    string         `json:"created_at"`
	ExpiresAt    string         `json:"expires_at"`
	LastActiveAt string         `json:"last_active_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.Token,
		arg.Username,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastActiveAt,
	)
	return err
}

const touchSessionActive = `-- name: TouchSessionActive :exec
UPDATE login_session SET last_active_at = ? WHERE token = ?
`

type TouchSessionActiveParams struct {
	LastActiveAt string `json:"last_active_at"`
	Token        string `json:"token"`
}

func (q *Queries) TouchSessionActive(ctx context.Context, arg TouchSessionActiveParams) error {
	_, err := q.db.ExecContext(ctx, touchSessionActive, arg.LastActiveAt, arg.Token)
	return err
}
