// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shape_cache.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteShapeCacheByTenant = `-- name: DeleteShapeCacheByTenant :exec
DELETE FROM shape_cache WHERE tenant_id = ?
`

func (q *Queries) DeleteShapeCacheByTenant(ctx context.Context, tenantID int64) error {
	_, err := q.db.ExecContext(ctx, deleteShapeCacheByTenant, tenantID)
	return err
}

const listShapeCacheByTenant = `-- name: ListShapeCacheByTenant :many
SELECT id, tenant_id, compartment_id, availability_domain, shape, architecture,
       ocpus, memory_in_gbs, processor_description, is_flexible,
       max_vnic_attachments, gpu_description, gpu_count,
       local_disk_description, networking_description, baseline_ocpu,
       last_synced_at, cloud_type
FROM shape_cache
WHERE tenant_id = ?
ORDER BY ocpus ASC
`

func (q *Queries) ListShapeCacheByTenant(ctx context.Context, tenantID int64) ([]ShapeCache, error) {
	rows, err := q.db.QueryContext(ctx, listShapeCacheByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShapeCache{}
	for rows.Next() {
		var i ShapeCache
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompartmentID,
			&i.AvailabilityDomain,
			&i.Shape,
			&i.Architecture,
			&i.Ocpus,
			&i.MemoryInGbs,
			&i.ProcessorDescription,
			&i.IsFlexible,
			&i.MaxVnicAttachments,
			&i.GpuDescription,
			&i.GpuCount,
			&i.LocalDiskDescription,
			&i.NetworkingDescription,
			&i.BaselineOcpu,
			&i.LastSyncedAt,
			&i.CloudType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShapeCacheByTenantAndArch = `-- name: ListShapeCacheByTenantAndArch :many
SELECT id, tenant_id, compartment_id, availability_domain, shape, architecture,
       ocpus, memory_in_gbs, processor_description, is_flexible,
       max_vnic_attachments, gpu_description, gpu_count,
       local_disk_description, networking_description, baseline_ocpu,
       last_synced_at, cloud_type
FROM shape_cache
WHERE tenant_id = ? AND architecture = ?
ORDER BY ocpus ASC
`

type ListShapeCacheByTenantAndArchParams struct {
	TenantID     int64  `json:"tenant_id"`
	Architecture string `json:"architecture"`
}

func (q *Queries) ListShapeCacheByTenantAndArch(ctx context.Context, arg ListShapeCacheByTenantAndArchParams) ([]ShapeCache, error) {
	rows, err := q.db.QueryContext(ctx, listShapeCacheByTenantAndArch, arg.TenantID, arg.Architecture)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShapeCache{}
	for rows.Next() {
		var i ShapeCache
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CompartmentID,
			&i.AvailabilityDomain,
			&i.Shape,
			&i.Architecture,
			&i.Ocpus,
			&i.MemoryInGbs,
			&i.ProcessorDescription,
			&i.IsFlexible,
			&i.MaxVnicAttachments,
			&i.GpuDescription,
			&i.GpuCount,
			&i.LocalDiskDescription,
			&i.NetworkingDescription,
			&i.BaselineOcpu,
			&i.LastSyncedAt,
			&i.CloudType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShapeCache = `-- name: UpsertShapeCache :exec
INSERT INTO shape_cache (
    tenant_id, compartment_id, availability_domain, shape, architecture,
    ocpus, memory_in_gbs, processor_description, is_flexible,
    max_vnic_attachments, gpu_description, gpu_count,
    local_disk_description, networking_description, baseline_ocpu,
    last_synced_at, cloud_type
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, 1
)
`

type UpsertShapeCacheParams struct {
	TenantID              int64           `json:"tenant_id"`
	CompartmentID         string          `json:"compartment_id"`
	AvailabilityDomain    sql.NullString  `json:"availability_domain"`
	Shape                 string          `json:"shape"`
	Architecture          string          `json:"architecture"`
	Ocpus                 sql.NullFloat64 `json:"ocpus"`
	MemoryInGbs           sql.NullFloat64 `json:"memory_in_gbs"`
	ProcessorDescription  sql.NullString  `json:"processor_description"`
	IsFlexible            int64           `json:"is_flexible"`
	MaxVnicAttachments    sql.NullInt64   `json:"max_vnic_attachments"`
	GpuDescription        sql.NullString  `json:"gpu_description"`
	GpuCount              sql.NullInt64   `json:"gpu_count"`
	LocalDiskDescription  sql.NullString  `json:"local_disk_description"`
	NetworkingDescription sql.NullString  `json:"networking_description"`
	BaselineOcpu          sql.NullFloat64 `json:"baseline_ocpu"`
	LastSyncedAt          string          `json:"last_synced_at"`
}

func (q *Queries) UpsertShapeCache(ctx context.Context, arg UpsertShapeCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertShapeCache,
		arg.TenantID,
		arg.CompartmentID,
		arg.AvailabilityDomain,
		arg.Shape,
		arg.Architecture,
		arg.Ocpus,
		arg.MemoryInGbs,
		arg.ProcessorDescription,
		arg.IsFlexible,
		arg.MaxVnicAttachments,
		arg.GpuDescription,
		arg.GpuCount,
		arg.LocalDiskDescription,
		arg.NetworkingDescription,
		arg.BaselineOcpu,
		arg.LastSyncedAt,
	)
	return err
}
