// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssl_certificate.sql

package repo

import (
	"context"
	"database/sql"
)

const countSslCertificates = `-- name: CountSslCertificates :one
SELECT COUNT(*) FROM ssl_certificate
`

func (q *Queries) CountSslCertificates(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSslCertificates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSslCertificate = `-- name: DeleteSslCertificate :exec
DELETE FROM ssl_certificate WHERE id = ?
`

func (q *Queries) DeleteSslCertificate(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSslCertificate, id)
	return err
}

const existsProxyConfigBySslCertId = `-- name: ExistsProxyConfigBySslCertId :one
SELECT COUNT(*) FROM proxy_config WHERE ssl_certificate_id = ?
`

func (q *Queries) ExistsProxyConfigBySslCertId(ctx context.Context, sslCertificateID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsProxyConfigBySslCertId, sslCertificateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsSslCertificateById = `-- name: ExistsSslCertificateById :one
SELECT COUNT(*) FROM ssl_certificate WHERE id = ?
`

func (q *Queries) ExistsSslCertificateById(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsSslCertificateById, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAllActiveSslCertificates = `-- name: FindAllActiveSslCertificates :many
SELECT id, domain, certificate_type, email, validation_method, auto_renew, certificate_status, issue_date, expire_date, certificate_path, private_key_path, create_time, update_time, dns_provider FROM ssl_certificate WHERE certificate_status = 'VALID'
`

func (q *Queries) FindAllActiveSslCertificates(ctx context.Context) ([]SslCertificate, error) {
	rows, err := q.db.QueryContext(ctx, findAllActiveSslCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SslCertificate{}
	for rows.Next() {
		var i SslCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CertificateType,
			&i.Email,
			&i.ValidationMethod,
			&i.AutoRenew,
			&i.CertificateStatus,
			&i.IssueDate,
			&i.ExpireDate,
			&i.CertificatePath,
			&i.PrivateKeyPath,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DnsProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSslCertificateByDomain = `-- name: FindSslCertificateByDomain :one
SELECT id, domain, certificate_type, email, validation_method, auto_renew, certificate_status, issue_date, expire_date, certificate_path, private_key_path, create_time, update_time, dns_provider FROM ssl_certificate WHERE domain = ? LIMIT 1
`

func (q *Queries) FindSslCertificateByDomain(ctx context.Context, domain string) (SslCertificate, error) {
	row := q.db.QueryRowContext(ctx, findSslCertificateByDomain, domain)
	var i SslCertificate
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CertificateType,
		&i.Email,
		&i.ValidationMethod,
		&i.AutoRenew,
		&i.CertificateStatus,
		&i.IssueDate,
		&i.ExpireDate,
		&i.CertificatePath,
		&i.PrivateKeyPath,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DnsProvider,
	)
	return i, err
}

const findSslCertificateById = `-- name: FindSslCertificateById :one
SELECT id, domain, certificate_type, email, validation_method, auto_renew, certificate_status, issue_date, expire_date, certificate_path, private_key_path, create_time, update_time, dns_provider FROM ssl_certificate WHERE id = ?
`

func (q *Queries) FindSslCertificateById(ctx context.Context, id int64) (SslCertificate, error) {
	row := q.db.QueryRowContext(ctx, findSslCertificateById, id)
	var i SslCertificate
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.CertificateType,
		&i.Email,
		&i.ValidationMethod,
		&i.AutoRenew,
		&i.CertificateStatus,
		&i.IssueDate,
		&i.ExpireDate,
		&i.CertificatePath,
		&i.PrivateKeyPath,
		&i.CreateTime,
		&i.UpdateTime,
		&i.DnsProvider,
	)
	return i, err
}

const insertSslCertificate = `-- name: InsertSslCertificate :one

INSERT INTO ssl_certificate (
    domain, certificate_type, email, validation_method, auto_renew,
    certificate_status, issue_date, expire_date, certificate_path,
    private_key_path, create_time, update_time, dns_provider
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertSslCertificateParams struct {
	Domain            string         `json:"domain"`
	CertificateType   string         `json:"certificate_type"`
	Email             sql.NullString `json:"email"`
	ValidationMethod  sql.NullString `json:"validation_method"`
	AutoRenew         sql.NullInt64  `json:"auto_renew"`
	CertificateStatus sql.NullString `json:"certificate_status"`
	IssueDate         sql.NullString `json:"issue_date"`
	ExpireDate        sql.NullString `json:"expire_date"`
	CertificatePath   sql.NullString `json:"certificate_path"`
	PrivateKeyPath    sql.NullString `json:"private_key_path"`
	CreateTime        sql.NullString `json:"create_time"`
	UpdateTime        sql.NullString `json:"update_time"`
	DnsProvider       sql.NullString `json:"dns_provider"`
}

// SslCertificate queries (Phase 12.1). ssl_certificate stores SSL cert
// lifecycle data: domain, type, status, paths to PEM files, auto-renew.
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) InsertSslCertificate(ctx context.Context, arg InsertSslCertificateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSslCertificate,
		arg.Domain,
		arg.CertificateType,
		arg.Email,
		arg.ValidationMethod,
		arg.AutoRenew,
		arg.CertificateStatus,
		arg.IssueDate,
		arg.ExpireDate,
		arg.CertificatePath,
		arg.PrivateKeyPath,
		arg.CreateTime,
		arg.UpdateTime,
		arg.DnsProvider,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listExpiringCertificates = `-- name: ListExpiringCertificates :many
SELECT id, domain, certificate_type, email, validation_method, auto_renew, certificate_status, issue_date, expire_date, certificate_path, private_key_path, create_time, update_time, dns_provider FROM ssl_certificate WHERE expire_date <= ? AND auto_renew = 1 AND certificate_type = 'LETS_ENCRYPT'
`

func (q *Queries) ListExpiringCertificates(ctx context.Context, expireDate sql.NullString) ([]SslCertificate, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringCertificates, expireDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SslCertificate{}
	for rows.Next() {
		var i SslCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CertificateType,
			&i.Email,
			&i.ValidationMethod,
			&i.AutoRenew,
			&i.CertificateStatus,
			&i.IssueDate,
			&i.ExpireDate,
			&i.CertificatePath,
			&i.PrivateKeyPath,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DnsProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSslCertificates = `-- name: ListSslCertificates :many
SELECT id, domain, certificate_type, email, validation_method, auto_renew, certificate_status, issue_date, expire_date, certificate_path, private_key_path, create_time, update_time, dns_provider FROM ssl_certificate ORDER BY create_time DESC LIMIT ? OFFSET ?
`

type ListSslCertificatesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSslCertificates(ctx context.Context, arg ListSslCertificatesParams) ([]SslCertificate, error) {
	rows, err := q.db.QueryContext(ctx, listSslCertificates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SslCertificate{}
	for rows.Next() {
		var i SslCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.CertificateType,
			&i.Email,
			&i.ValidationMethod,
			&i.AutoRenew,
			&i.CertificateStatus,
			&i.IssueDate,
			&i.ExpireDate,
			&i.CertificatePath,
			&i.PrivateKeyPath,
			&i.CreateTime,
			&i.UpdateTime,
			&i.DnsProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSslCertificate = `-- name: UpdateSslCertificate :exec
UPDATE ssl_certificate
SET domain = ?, certificate_type = ?, email = ?, validation_method = ?,
    auto_renew = ?, certificate_status = ?, issue_date = ?, expire_date = ?,
    certificate_path = ?, private_key_path = ?, update_time = ?, dns_provider = ?
WHERE id = ?
`

type UpdateSslCertificateParams struct {
	Domain            string         `json:"domain"`
	CertificateType   string         `json:"certificate_type"`
	Email             sql.NullString `json:"email"`
	ValidationMethod  sql.NullString `json:"validation_method"`
	AutoRenew         sql.NullInt64  `json:"auto_renew"`
	CertificateStatus sql.NullString `json:"certificate_status"`
	IssueDate         sql.NullString `json:"issue_date"`
	ExpireDate        sql.NullString `json:"expire_date"`
	CertificatePath   sql.NullString `json:"certificate_path"`
	PrivateKeyPath    sql.NullString `json:"private_key_path"`
	UpdateTime        sql.NullString `json:"update_time"`
	DnsProvider       sql.NullString `json:"dns_provider"`
	ID                int64          `json:"id"`
}

func (q *Queries) UpdateSslCertificate(ctx context.Context, arg UpdateSslCertificateParams) error {
	_, err := q.db.ExecContext(ctx, updateSslCertificate,
		arg.Domain,
		arg.CertificateType,
		arg.Email,
		arg.ValidationMethod,
		arg.AutoRenew,
		arg.CertificateStatus,
		arg.IssueDate,
		arg.ExpireDate,
		arg.CertificatePath,
		arg.PrivateKeyPath,
		arg.UpdateTime,
		arg.DnsProvider,
		arg.ID,
	)
	return err
}
