// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package repo

import (
	"context"
)

const countAppVersion = `-- name: CountAppVersion :one
SELECT count(*) FROM app_version
`

func (q *Queries) CountAppVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppVersion)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAppVersion = `-- name: GetAppVersion :one
SELECT id, current_version, latest_version, deploy_type, create_time, update_time
FROM app_version
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetAppVersion(ctx context.Context) (AppVersion, error) {
	row := q.db.QueryRowContext(ctx, getAppVersion)
	var i AppVersion
	err := row.Scan(
		&i.ID,
		&i.CurrentVersion,
		&i.LatestVersion,
		&i.DeployType,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const seedAppVersion = `-- name: SeedAppVersion :exec
INSERT OR IGNORE INTO app_version (id, current_version, latest_version, deploy_type, create_time, update_time)
VALUES (1, ?, ?, ?, ?, ?)
`

type SeedAppVersionParams struct {
	CurrentVersion string `json:"current_version"`
	LatestVersion  string `json:"latest_version"`
	DeployType     string `json:"deploy_type"`
	CreateTime     string `json:"create_time"`
	UpdateTime     string `json:"update_time"`
}

func (q *Queries) SeedAppVersion(ctx context.Context, arg SeedAppVersionParams) error {
	_, err := q.db.ExecContext(ctx, seedAppVersion,
		arg.CurrentVersion,
		arg.LatestVersion,
		arg.DeployType,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const updateAppVersion = `-- name: UpdateAppVersion :exec
UPDATE app_version
SET current_version = ?, latest_version = ?, update_time = ?
WHERE id = 1
`

type UpdateAppVersionParams struct {
	CurrentVersion string `json:"current_version"`
	LatestVersion  string `json:"latest_version"`
	UpdateTime     string `json:"update_time"`
}

func (q *Queries) UpdateAppVersion(ctx context.Context, arg UpdateAppVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateAppVersion, arg.CurrentVersion, arg.LatestVersion, arg.UpdateTime)
	return err
}
