// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_config.sql

package repo

import (
	"context"
	"database/sql"
)

const findConfigByKey = `-- name: FindConfigByKey :one

SELECT id, config_key, config_value, config_enabled, last_modified
FROM system_config
WHERE config_key = ?
LIMIT 1
`

// system_config is the runtime KV store (config_key UNIQUE).
// Boolean configs use the config_enabled column (INTEGER 0/1);
// string configs use config_value. Mirrors Java SystemConfigService.
func (q *Queries) FindConfigByKey(ctx context.Context, configKey sql.NullString) (SystemConfig, error) {
	row := q.db.QueryRowContext(ctx, findConfigByKey, configKey)
	var i SystemConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.ConfigEnabled,
		&i.LastModified,
	)
	return i, err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO system_config (config_key, config_value, config_enabled, last_modified)
VALUES (?, ?, ?, ?)
ON CONFLICT(config_key) DO UPDATE SET
    config_value = excluded.config_value,
    config_enabled = excluded.config_enabled,
    last_modified = excluded.last_modified
`

type UpsertConfigParams struct {
	ConfigKey     sql.NullString `json:"config_key"`
	ConfigValue   sql.NullString `json:"config_value"`
	ConfigEnabled sql.NullInt64  `json:"config_enabled"`
	LastModified  sql.NullString `json:"last_modified"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.ConfigEnabled,
		arg.LastModified,
	)
	return err
}

const upsertConfigEnabled = `-- name: UpsertConfigEnabled :exec
INSERT INTO system_config (config_key, config_value, config_enabled, last_modified)
VALUES (?, ?, ?, ?)
ON CONFLICT(config_key) DO UPDATE SET
    config_enabled = excluded.config_enabled,
    last_modified = excluded.last_modified
`

type UpsertConfigEnabledParams struct {
	ConfigKey     sql.NullString `json:"config_key"`
	ConfigValue   sql.NullString `json:"config_value"`
	ConfigEnabled sql.NullInt64  `json:"config_enabled"`
	LastModified  sql.NullString `json:"last_modified"`
}

func (q *Queries) UpsertConfigEnabled(ctx context.Context, arg UpsertConfigEnabledParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfigEnabled,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.ConfigEnabled,
		arg.LastModified,
	)
	return err
}

const upsertConfigValue = `-- name: UpsertConfigValue :exec
INSERT INTO system_config (config_key, config_value, config_enabled, last_modified)
VALUES (?, ?, ?, ?)
ON CONFLICT(config_key) DO UPDATE SET
    config_value = excluded.config_value,
    last_modified = excluded.last_modified
`

type UpsertConfigValueParams struct {
	ConfigKey     sql.NullString `json:"config_key"`
	ConfigValue   sql.NullString `json:"config_value"`
	ConfigEnabled sql.NullInt64  `json:"config_enabled"`
	LastModified  sql.NullString `json:"last_modified"`
}

func (q *Queries) UpsertConfigValue(ctx context.Context, arg UpsertConfigValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfigValue,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.ConfigEnabled,
		arg.LastModified,
	)
	return err
}
