// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_email_config_ext.sql

package repo

import (
	"context"
	"database/sql"
)

const countTenantEmailConfigs = `-- name: CountTenantEmailConfigs :one
SELECT COUNT(*) FROM tenant_email_config WHERE active = 1
`

func (q *Queries) CountTenantEmailConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenantEmailConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findTenantEmailConfigById = `-- name: FindTenantEmailConfigById :one

SELECT id, tenant_id, domain_id, domain_name, sender_id, credential_id,
       smtp_username, smtp_password, smtp_host, smtp_port, sender_email,
       dkim_id, cname_record_value, active, created_time, daily_email_limit,
       today_sent_count, last_reset_date, dbs_record_ids_str
FROM tenant_email_config WHERE id = ?
`

// Extended tenant email config queries (Phase 12.2). OCI provisioning fields,
// daily send tracking, and admin list endpoint.
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) FindTenantEmailConfigById(ctx context.Context, id int64) (TenantEmailConfig, error) {
	row := q.db.QueryRowContext(ctx, findTenantEmailConfigById, id)
	var i TenantEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DomainID,
		&i.DomainName,
		&i.SenderID,
		&i.CredentialID,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SenderEmail,
		&i.DkimID,
		&i.CnameRecordValue,
		&i.Active,
		&i.CreatedTime,
		&i.DailyEmailLimit,
		&i.TodaySentCount,
		&i.LastResetDate,
		&i.DbsRecordIdsStr,
	)
	return i, err
}

const listTenantEmailConfigs = `-- name: ListTenantEmailConfigs :many
SELECT tec.id, tec.tenant_id, tec.domain_name, tec.smtp_username,
       tec.smtp_host, tec.smtp_port, tec.sender_email, tec.active,
       tec.created_time, tec.daily_email_limit, tec.today_sent_count,
       t.user_name AS tenant_name
FROM tenant_email_config tec
LEFT JOIN tenant t ON tec.tenant_id = t.id
WHERE tec.active = 1
ORDER BY tec.id DESC
LIMIT ? OFFSET ?
`

type ListTenantEmailConfigsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListTenantEmailConfigsRow struct {
	ID              int64          `json:"id"`
	TenantID        sql.NullInt64  `json:"tenant_id"`
	DomainName      sql.NullString `json:"domain_name"`
	SmtpUsername    sql.NullString `json:"smtp_username"`
	SmtpHost        sql.NullString `json:"smtp_host"`
	SmtpPort        sql.NullString `json:"smtp_port"`
	SenderEmail     sql.NullString `json:"sender_email"`
	Active          sql.NullInt64  `json:"active"`
	CreatedTime     sql.NullString `json:"created_time"`
	DailyEmailLimit sql.NullInt64  `json:"daily_email_limit"`
	TodaySentCount  sql.NullInt64  `json:"today_sent_count"`
	TenantName      sql.NullString `json:"tenant_name"`
}

func (q *Queries) ListTenantEmailConfigs(ctx context.Context, arg ListTenantEmailConfigsParams) ([]ListTenantEmailConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantEmailConfigs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantEmailConfigsRow{}
	for rows.Next() {
		var i ListTenantEmailConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainName,
			&i.SmtpUsername,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SenderEmail,
			&i.Active,
			&i.CreatedTime,
			&i.DailyEmailLimit,
			&i.TodaySentCount,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantEmailSentCount = `-- name: UpdateTenantEmailSentCount :exec
UPDATE tenant_email_config SET today_sent_count = ?, last_reset_date = ?
WHERE id = ?
`

type UpdateTenantEmailSentCountParams struct {
	TodaySentCount sql.NullInt64  `json:"today_sent_count"`
	LastResetDate  sql.NullString `json:"last_reset_date"`
	ID             int64          `json:"id"`
}

func (q *Queries) UpdateTenantEmailSentCount(ctx context.Context, arg UpdateTenantEmailSentCountParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantEmailSentCount, arg.TodaySentCount, arg.LastResetDate, arg.ID)
	return err
}

const upsertTenantEmailConfigFull = `-- name: UpsertTenantEmailConfigFull :exec
INSERT INTO tenant_email_config (
    tenant_id, domain_id, domain_name, sender_id, credential_id,
    smtp_username, smtp_password, smtp_host, smtp_port, sender_email,
    dkim_id, cname_record_value, active, created_time, daily_email_limit,
    today_sent_count, last_reset_date, dbs_record_ids_str
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tenant_id) DO UPDATE SET
    domain_id = excluded.domain_id,
    domain_name = excluded.domain_name,
    sender_id = excluded.sender_id,
    credential_id = excluded.credential_id,
    smtp_username = excluded.smtp_username,
    smtp_password = excluded.smtp_password,
    smtp_host = excluded.smtp_host,
    smtp_port = excluded.smtp_port,
    sender_email = excluded.sender_email,
    dkim_id = excluded.dkim_id,
    cname_record_value = excluded.cname_record_value,
    active = excluded.active,
    created_time = excluded.created_time,
    daily_email_limit = excluded.daily_email_limit,
    today_sent_count = excluded.today_sent_count,
    last_reset_date = excluded.last_reset_date,
    dbs_record_ids_str = excluded.dbs_record_ids_str
`

type UpsertTenantEmailConfigFullParams struct {
	TenantID         sql.NullInt64  `json:"tenant_id"`
	DomainID         sql.NullString `json:"domain_id"`
	DomainName       sql.NullString `json:"domain_name"`
	SenderID         sql.NullString `json:"sender_id"`
	CredentialID     sql.NullString `json:"credential_id"`
	SmtpUsername     sql.NullString `json:"smtp_username"`
	SmtpPassword     sql.NullString `json:"smtp_password"`
	SmtpHost         sql.NullString `json:"smtp_host"`
	SmtpPort         sql.NullString `json:"smtp_port"`
	SenderEmail      sql.NullString `json:"sender_email"`
	DkimID           sql.NullString `json:"dkim_id"`
	CnameRecordValue sql.NullString `json:"cname_record_value"`
	Active           sql.NullInt64  `json:"active"`
	CreatedTime      sql.NullString `json:"created_time"`
	DailyEmailLimit  sql.NullInt64  `json:"daily_email_limit"`
	TodaySentCount   sql.NullInt64  `json:"today_sent_count"`
	LastResetDate    sql.NullString `json:"last_reset_date"`
	DbsRecordIdsStr  sql.NullString `json:"dbs_record_ids_str"`
}

func (q *Queries) UpsertTenantEmailConfigFull(ctx context.Context, arg UpsertTenantEmailConfigFullParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenantEmailConfigFull,
		arg.TenantID,
		arg.DomainID,
		arg.DomainName,
		arg.SenderID,
		arg.CredentialID,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SenderEmail,
		arg.DkimID,
		arg.CnameRecordValue,
		arg.Active,
		arg.CreatedTime,
		arg.DailyEmailLimit,
		arg.TodaySentCount,
		arg.LastResetDate,
		arg.DbsRecordIdsStr,
	)
	return err
}
