// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_email_config.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteTenantEmailConfig = `-- name: DeleteTenantEmailConfig :exec
DELETE FROM tenant_email_config WHERE tenant_id = ?
`

func (q *Queries) DeleteTenantEmailConfig(ctx context.Context, tenantID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTenantEmailConfig, tenantID)
	return err
}

const findTenantEmailConfigByTenantId = `-- name: FindTenantEmailConfigByTenantId :one

SELECT id, tenant_id, domain_id, domain_name, sender_id, credential_id,
       smtp_username, smtp_password, smtp_host, smtp_port, sender_email,
       dkim_id, cname_record_value, active, created_time, daily_email_limit,
       today_sent_count, last_reset_date, dbs_record_ids_str
FROM tenant_email_config WHERE tenant_id = ?
`

// Tenant email config queries (Phase 9). tenant_email_config stores SES/SMTP
// configuration per tenant for email service.
func (q *Queries) FindTenantEmailConfigByTenantId(ctx context.Context, tenantID sql.NullInt64) (TenantEmailConfig, error) {
	row := q.db.QueryRowContext(ctx, findTenantEmailConfigByTenantId, tenantID)
	var i TenantEmailConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DomainID,
		&i.DomainName,
		&i.SenderID,
		&i.CredentialID,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SenderEmail,
		&i.DkimID,
		&i.CnameRecordValue,
		&i.Active,
		&i.CreatedTime,
		&i.DailyEmailLimit,
		&i.TodaySentCount,
		&i.LastResetDate,
		&i.DbsRecordIdsStr,
	)
	return i, err
}

const updateTenantEmailActive = `-- name: UpdateTenantEmailActive :exec
UPDATE tenant_email_config SET active = ? WHERE tenant_id = ?
`

type UpdateTenantEmailActiveParams struct {
	Active   sql.NullInt64 `json:"active"`
	TenantID sql.NullInt64 `json:"tenant_id"`
}

func (q *Queries) UpdateTenantEmailActive(ctx context.Context, arg UpdateTenantEmailActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantEmailActive, arg.Active, arg.TenantID)
	return err
}

const upsertTenantEmailConfig = `-- name: UpsertTenantEmailConfig :exec
INSERT INTO tenant_email_config (
    tenant_id, domain_name, smtp_username, smtp_password, smtp_host, smtp_port,
    sender_email, active, created_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tenant_id) DO UPDATE SET
    domain_name = excluded.domain_name,
    smtp_username = excluded.smtp_username,
    smtp_password = excluded.smtp_password,
    smtp_host = excluded.smtp_host,
    smtp_port = excluded.smtp_port,
    sender_email = excluded.sender_email,
    active = excluded.active
`

type UpsertTenantEmailConfigParams struct {
	TenantID     sql.NullInt64  `json:"tenant_id"`
	DomainName   sql.NullString `json:"domain_name"`
	SmtpUsername sql.NullString `json:"smtp_username"`
	SmtpPassword sql.NullString `json:"smtp_password"`
	SmtpHost     sql.NullString `json:"smtp_host"`
	SmtpPort     sql.NullString `json:"smtp_port"`
	SenderEmail  sql.NullString `json:"sender_email"`
	Active       sql.NullInt64  `json:"active"`
	CreatedTime  sql.NullString `json:"created_time"`
}

func (q *Queries) UpsertTenantEmailConfig(ctx context.Context, arg UpsertTenantEmailConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertTenantEmailConfig,
		arg.TenantID,
		arg.DomainName,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SenderEmail,
		arg.Active,
		arg.CreatedTime,
	)
	return err
}
