// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_social.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteTenantSocial = `-- name: DeleteTenantSocial :exec
DELETE FROM tenant_social WHERE id = ?
`

func (q *Queries) DeleteTenantSocial(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTenantSocial, id)
	return err
}

const findTenantSocialByType = `-- name: FindTenantSocialByType :one
SELECT id, tenant_id, tenancy, cloud_type, client_id, client_secret,
       social_type_str, third_login_address, redirect_url, social_status
FROM tenant_social WHERE tenant_id = ? AND social_type_str = ?
`

type FindTenantSocialByTypeParams struct {
	TenantID      sql.NullInt64  `json:"tenant_id"`
	SocialTypeStr sql.NullString `json:"social_type_str"`
}

func (q *Queries) FindTenantSocialByType(ctx context.Context, arg FindTenantSocialByTypeParams) (TenantSocial, error) {
	row := q.db.QueryRowContext(ctx, findTenantSocialByType, arg.TenantID, arg.SocialTypeStr)
	var i TenantSocial
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Tenancy,
		&i.CloudType,
		&i.ClientID,
		&i.ClientSecret,
		&i.SocialTypeStr,
		&i.ThirdLoginAddress,
		&i.RedirectUrl,
		&i.SocialStatus,
	)
	return i, err
}

const insertTenantSocial = `-- name: InsertTenantSocial :exec
INSERT INTO tenant_social (
    tenant_id, tenancy, cloud_type, client_id, client_secret,
    social_type_str, third_login_address, redirect_url, social_status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTenantSocialParams struct {
	TenantID          sql.NullInt64  `json:"tenant_id"`
	Tenancy           sql.NullString `json:"tenancy"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	ClientID          sql.NullString `json:"client_id"`
	ClientSecret      sql.NullString `json:"client_secret"`
	SocialTypeStr     sql.NullString `json:"social_type_str"`
	ThirdLoginAddress sql.NullString `json:"third_login_address"`
	RedirectUrl       sql.NullString `json:"redirect_url"`
	SocialStatus      sql.NullString `json:"social_status"`
}

func (q *Queries) InsertTenantSocial(ctx context.Context, arg InsertTenantSocialParams) error {
	_, err := q.db.ExecContext(ctx, insertTenantSocial,
		arg.TenantID,
		arg.Tenancy,
		arg.CloudType,
		arg.ClientID,
		arg.ClientSecret,
		arg.SocialTypeStr,
		arg.ThirdLoginAddress,
		arg.RedirectUrl,
		arg.SocialStatus,
	)
	return err
}

const listTenantSocialByTenantId = `-- name: ListTenantSocialByTenantId :many

SELECT id, tenant_id, tenancy, cloud_type, client_id, client_secret,
       social_type_str, third_login_address, redirect_url, social_status
FROM tenant_social WHERE tenant_id = ? ORDER BY id
`

// Tenant social config queries (Phase 9). tenant_social stores third-party OAuth
// configuration per tenant (Google, GitHub, Microsoft, etc.).
func (q *Queries) ListTenantSocialByTenantId(ctx context.Context, tenantID sql.NullInt64) ([]TenantSocial, error) {
	rows, err := q.db.QueryContext(ctx, listTenantSocialByTenantId, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantSocial{}
	for rows.Next() {
		var i TenantSocial
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Tenancy,
			&i.CloudType,
			&i.ClientID,
			&i.ClientSecret,
			&i.SocialTypeStr,
			&i.ThirdLoginAddress,
			&i.RedirectUrl,
			&i.SocialStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantSocial = `-- name: UpdateTenantSocial :exec
UPDATE tenant_social
SET client_id = ?, client_secret = ?, redirect_url = ?, third_login_address = ?
WHERE id = ?
`

type UpdateTenantSocialParams struct {
	ClientID          sql.NullString `json:"client_id"`
	ClientSecret      sql.NullString `json:"client_secret"`
	RedirectUrl       sql.NullString `json:"redirect_url"`
	ThirdLoginAddress sql.NullString `json:"third_login_address"`
	ID                int64          `json:"id"`
}

func (q *Queries) UpdateTenantSocial(ctx context.Context, arg UpdateTenantSocialParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantSocial,
		arg.ClientID,
		arg.ClientSecret,
		arg.RedirectUrl,
		arg.ThirdLoginAddress,
		arg.ID,
	)
	return err
}

const updateTenantSocialStatus = `-- name: UpdateTenantSocialStatus :exec
UPDATE tenant_social SET social_status = ? WHERE id = ?
`

type UpdateTenantSocialStatusParams struct {
	SocialStatus sql.NullString `json:"social_status"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateTenantSocialStatus(ctx context.Context, arg UpdateTenantSocialStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantSocialStatus, arg.SocialStatus, arg.ID)
	return err
}
