// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenant WHERE id = ?
`

func (q *Queries) DeleteTenant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTenant, id)
	return err
}

const findTenantByID = `-- name: FindTenantByID :one
SELECT id, tenant_id, user_name, fingerprint, tenancy, region, key_file, created_at, api_synced, enable_icmp, enable_all_protocol, is_home_region, paren_id, tenancy_name, tenancy_des, account_type, cloud_type, region_en, id_str, email_address, email_enable, transfer_status, transfer_amount, is_active, key_file_blob FROM tenant WHERE id = ?
`

func (q *Queries) FindTenantByID(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, findTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserName,
		&i.Fingerprint,
		&i.Tenancy,
		&i.Region,
		&i.KeyFile,
		&i.CreatedAt,
		&i.ApiSynced,
		&i.EnableIcmp,
		&i.EnableAllProtocol,
		&i.IsHomeRegion,
		&i.ParenID,
		&i.TenancyName,
		&i.TenancyDes,
		&i.AccountType,
		&i.CloudType,
		&i.RegionEn,
		&i.IDStr,
		&i.EmailAddress,
		&i.EmailEnable,
		&i.TransferStatus,
		&i.TransferAmount,
		&i.IsActive,
		&i.KeyFileBlob,
	)
	return i, err
}

const findTenantsByParenId = `-- name: FindTenantsByParenId :many
SELECT
    id, tenant_id, user_name, fingerprint, tenancy, region, created_at,
    api_synced, is_home_region, paren_id, tenancy_name, account_type,
    cloud_type, is_active
FROM tenant
WHERE paren_id = ?
ORDER BY id
`

type FindTenantsByParenIdRow struct {
	ID           int64          `json:"id"`
	TenantID     sql.NullString `json:"tenant_id"`
	UserName     sql.NullString `json:"user_name"`
	Fingerprint  sql.NullString `json:"fingerprint"`
	Tenancy      sql.NullString `json:"tenancy"`
	Region       sql.NullString `json:"region"`
	CreatedAt    sql.NullString `json:"created_at"`
	ApiSynced    sql.NullInt64  `json:"api_synced"`
	IsHomeRegion sql.NullInt64  `json:"is_home_region"`
	ParenID      sql.NullInt64  `json:"paren_id"`
	TenancyName  sql.NullString `json:"tenancy_name"`
	AccountType  sql.NullString `json:"account_type"`
	CloudType    sql.NullInt64  `json:"cloud_type"`
	IsActive     sql.NullInt64  `json:"is_active"`
}

func (q *Queries) FindTenantsByParenId(ctx context.Context, parenID sql.NullInt64) ([]FindTenantsByParenIdRow, error) {
	rows, err := q.db.QueryContext(ctx, findTenantsByParenId, parenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTenantsByParenIdRow{}
	for rows.Next() {
		var i FindTenantsByParenIdRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserName,
			&i.Fingerprint,
			&i.Tenancy,
			&i.Region,
			&i.CreatedAt,
			&i.ApiSynced,
			&i.IsHomeRegion,
			&i.ParenID,
			&i.TenancyName,
			&i.AccountType,
			&i.CloudType,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO tenant (
    tenant_id, user_name, fingerprint, tenancy, region, key_file_blob,
    created_at, cloud_type, is_home_region, account_type, tenancy_name,
    is_active
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTenantParams struct {
	TenantID     sql.NullString `json:"tenant_id"`
	UserName     sql.NullString `json:"user_name"`
	Fingerprint  sql.NullString `json:"fingerprint"`
	Tenancy      sql.NullString `json:"tenancy"`
	Region       sql.NullString `json:"region"`
	KeyFileBlob  sql.NullString `json:"key_file_blob"`
	CreatedAt    sql.NullString `json:"created_at"`
	CloudType    sql.NullInt64  `json:"cloud_type"`
	IsHomeRegion sql.NullInt64  `json:"is_home_region"`
	AccountType  sql.NullString `json:"account_type"`
	TenancyName  sql.NullString `json:"tenancy_name"`
	IsActive     sql.NullInt64  `json:"is_active"`
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.ExecContext(ctx, insertTenant,
		arg.TenantID,
		arg.UserName,
		arg.Fingerprint,
		arg.Tenancy,
		arg.Region,
		arg.KeyFileBlob,
		arg.CreatedAt,
		arg.CloudType,
		arg.IsHomeRegion,
		arg.AccountType,
		arg.TenancyName,
		arg.IsActive,
	)
	return err
}

const listTenants = `-- name: ListTenants :many

SELECT
    id, tenant_id, user_name, fingerprint, tenancy, region, created_at,
    api_synced, enable_icmp, enable_all_protocol, is_home_region, paren_id,
    tenancy_name, tenancy_des, account_type, cloud_type, region_en, id_str,
    email_address, email_enable, transfer_status, transfer_amount, is_active
FROM tenant
ORDER BY id
`

type ListTenantsRow struct {
	ID                int64          `json:"id"`
	TenantID          sql.NullString `json:"tenant_id"`
	UserName          sql.NullString `json:"user_name"`
	Fingerprint       sql.NullString `json:"fingerprint"`
	Tenancy           sql.NullString `json:"tenancy"`
	Region            sql.NullString `json:"region"`
	CreatedAt         sql.NullString `json:"created_at"`
	ApiSynced         sql.NullInt64  `json:"api_synced"`
	EnableIcmp        sql.NullInt64  `json:"enable_icmp"`
	EnableAllProtocol sql.NullInt64  `json:"enable_all_protocol"`
	IsHomeRegion      sql.NullInt64  `json:"is_home_region"`
	ParenID           sql.NullInt64  `json:"paren_id"`
	TenancyName       sql.NullString `json:"tenancy_name"`
	TenancyDes        sql.NullString `json:"tenancy_des"`
	AccountType       sql.NullString `json:"account_type"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	RegionEn          sql.NullString `json:"region_en"`
	IDStr             sql.NullString `json:"id_str"`
	EmailAddress      sql.NullString `json:"email_address"`
	EmailEnable       sql.NullInt64  `json:"email_enable"`
	TransferStatus    sql.NullInt64  `json:"transfer_status"`
	TransferAmount    sql.NullString `json:"transfer_amount"`
	IsActive          sql.NullInt64  `json:"is_active"`
}

// Tenant queries (Phase 3). key_file_blob holds the AES-256-GCM encrypted
// PEM (base64). List/mask queries deliberately omit key_file/key_file_blob.
func (q *Queries) ListTenants(ctx context.Context) ([]ListTenantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserName,
			&i.Fingerprint,
			&i.Tenancy,
			&i.Region,
			&i.CreatedAt,
			&i.ApiSynced,
			&i.EnableIcmp,
			&i.EnableAllProtocol,
			&i.IsHomeRegion,
			&i.ParenID,
			&i.TenancyName,
			&i.TenancyDes,
			&i.AccountType,
			&i.CloudType,
			&i.RegionEn,
			&i.IDStr,
			&i.EmailAddress,
			&i.EmailEnable,
			&i.TransferStatus,
			&i.TransferAmount,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsWithCounts = `-- name: ListTenantsWithCounts :many
SELECT
    t.id, t.tenant_id, t.user_name, t.fingerprint, t.tenancy, t.region, t.created_at,
    t.api_synced, t.enable_icmp, t.enable_all_protocol, t.is_home_region, t.paren_id,
    t.tenancy_name, t.tenancy_des, t.account_type, t.cloud_type, t.region_en, t.id_str,
    t.email_address, t.email_enable, t.transfer_status, t.transfer_amount, t.is_active,
    (SELECT COUNT(*) FROM instance_detail WHERE tenant_id = t.id) AS instance_count,
    (SELECT rd.register_time FROM register_detail rd WHERE rd.tenant_id = t.tenant_id LIMIT 1) AS register_time,
    (SELECT COUNT(*) FROM boot_instance b WHERE b.tenant_id = t.id AND b.status = 1) AS boot_count,
    (SELECT COUNT(*) FROM tenant c WHERE c.paren_id = t.id) AS child_count
FROM tenant t
ORDER BY t.id
`

type ListTenantsWithCountsRow struct {
	ID                int64          `json:"id"`
	TenantID          sql.NullString `json:"tenant_id"`
	UserName          sql.NullString `json:"user_name"`
	Fingerprint       sql.NullString `json:"fingerprint"`
	Tenancy           sql.NullString `json:"tenancy"`
	Region            sql.NullString `json:"region"`
	CreatedAt         sql.NullString `json:"created_at"`
	ApiSynced         sql.NullInt64  `json:"api_synced"`
	EnableIcmp        sql.NullInt64  `json:"enable_icmp"`
	EnableAllProtocol sql.NullInt64  `json:"enable_all_protocol"`
	IsHomeRegion      sql.NullInt64  `json:"is_home_region"`
	ParenID           sql.NullInt64  `json:"paren_id"`
	TenancyName       sql.NullString `json:"tenancy_name"`
	TenancyDes        sql.NullString `json:"tenancy_des"`
	AccountType       sql.NullString `json:"account_type"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	RegionEn          sql.NullString `json:"region_en"`
	IDStr             sql.NullString `json:"id_str"`
	EmailAddress      sql.NullString `json:"email_address"`
	EmailEnable       sql.NullInt64  `json:"email_enable"`
	TransferStatus    sql.NullInt64  `json:"transfer_status"`
	TransferAmount    sql.NullString `json:"transfer_amount"`
	IsActive          sql.NullInt64  `json:"is_active"`
	InstanceCount     int64          `json:"instance_count"`
	RegisterTime      sql.NullString `json:"register_time"`
	BootCount         int64          `json:"boot_count"`
	ChildCount        int64          `json:"child_count"`
}

// Aggregates tenant + register_detail.register_time + boot_instance count
// (status=1) + child count in a single round-trip, replacing the per-tenant
// FindRegisterDetailByTenantId / CountBootInstancesByTenantId / CountTenantChildren
// fan-out in service.TenantService.List. All three enrichments are correlated
// subqueries: this avoids the row-multiplication a LEFT JOIN would introduce
// when register_detail has duplicate tenant_id rows (UpsertRegisterDetail uses
// INSERT OR REPLACE with no unique constraint), and matches the first-row
// semantics of FindRegisterDetailByTenantId (:one).
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) ListTenantsWithCounts(ctx context.Context) ([]ListTenantsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsWithCountsRow{}
	for rows.Next() {
		var i ListTenantsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserName,
			&i.Fingerprint,
			&i.Tenancy,
			&i.Region,
			&i.CreatedAt,
			&i.ApiSynced,
			&i.EnableIcmp,
			&i.EnableAllProtocol,
			&i.IsHomeRegion,
			&i.ParenID,
			&i.TenancyName,
			&i.TenancyDes,
			&i.AccountType,
			&i.CloudType,
			&i.RegionEn,
			&i.IDStr,
			&i.EmailAddress,
			&i.EmailEnable,
			&i.TransferStatus,
			&i.TransferAmount,
			&i.IsActive,
			&i.InstanceCount,
			&i.RegisterTime,
			&i.BootCount,
			&i.ChildCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantApiSynced = `-- name: SetTenantApiSynced :exec
UPDATE tenant SET api_synced = ? WHERE id = ?
`

type SetTenantApiSyncedParams struct {
	ApiSynced sql.NullInt64 `json:"api_synced"`
	ID        int64         `json:"id"`
}

func (q *Queries) SetTenantApiSynced(ctx context.Context, arg SetTenantApiSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setTenantApiSynced, arg.ApiSynced, arg.ID)
	return err
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenant
SET tenant_id = ?, user_name = ?, fingerprint = ?, tenancy = ?, region = ?,
    key_file_blob = ?, cloud_type = ?, is_home_region = ?, account_type = ?,
    tenancy_name = ?
WHERE id = ?
`

type UpdateTenantParams struct {
	TenantID     sql.NullString `json:"tenant_id"`
	UserName     sql.NullString `json:"user_name"`
	Fingerprint  sql.NullString `json:"fingerprint"`
	Tenancy      sql.NullString `json:"tenancy"`
	Region       sql.NullString `json:"region"`
	KeyFileBlob  sql.NullString `json:"key_file_blob"`
	CloudType    sql.NullInt64  `json:"cloud_type"`
	IsHomeRegion sql.NullInt64  `json:"is_home_region"`
	AccountType  sql.NullString `json:"account_type"`
	TenancyName  sql.NullString `json:"tenancy_name"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.ExecContext(ctx, updateTenant,
		arg.TenantID,
		arg.UserName,
		arg.Fingerprint,
		arg.Tenancy,
		arg.Region,
		arg.KeyFileBlob,
		arg.CloudType,
		arg.IsHomeRegion,
		arg.AccountType,
		arg.TenancyName,
		arg.ID,
	)
	return err
}
