// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_ext.sql

package repo

import (
	"context"
	"database/sql"
)

const findTenantFullByID = `-- name: FindTenantFullByID :one
SELECT id, tenant_id, user_name, fingerprint, tenancy, region, created_at,
       api_synced, enable_icmp, enable_all_protocol, is_home_region, paren_id,
       tenancy_name, tenancy_des, account_type, cloud_type, region_en, id_str,
       email_address, email_enable, transfer_status, transfer_amount, is_active,
       key_file_blob
FROM tenant WHERE id = ?
`

type FindTenantFullByIDRow struct {
	ID                int64          `json:"id"`
	TenantID          sql.NullString `json:"tenant_id"`
	UserName          sql.NullString `json:"user_name"`
	Fingerprint       sql.NullString `json:"fingerprint"`
	Tenancy           sql.NullString `json:"tenancy"`
	Region            sql.NullString `json:"region"`
	CreatedAt         sql.NullString `json:"created_at"`
	ApiSynced         sql.NullInt64  `json:"api_synced"`
	EnableIcmp        sql.NullInt64  `json:"enable_icmp"`
	EnableAllProtocol sql.NullInt64  `json:"enable_all_protocol"`
	IsHomeRegion      sql.NullInt64  `json:"is_home_region"`
	ParenID           sql.NullInt64  `json:"paren_id"`
	TenancyName       sql.NullString `json:"tenancy_name"`
	TenancyDes        sql.NullString `json:"tenancy_des"`
	AccountType       sql.NullString `json:"account_type"`
	CloudType         sql.NullInt64  `json:"cloud_type"`
	RegionEn          sql.NullString `json:"region_en"`
	IDStr             sql.NullString `json:"id_str"`
	EmailAddress      sql.NullString `json:"email_address"`
	EmailEnable       sql.NullInt64  `json:"email_enable"`
	TransferStatus    sql.NullInt64  `json:"transfer_status"`
	TransferAmount    sql.NullString `json:"transfer_amount"`
	IsActive          sql.NullInt64  `json:"is_active"`
	KeyFileBlob       sql.NullString `json:"key_file_blob"`
}

func (q *Queries) FindTenantFullByID(ctx context.Context, id int64) (FindTenantFullByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findTenantFullByID, id)
	var i FindTenantFullByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserName,
		&i.Fingerprint,
		&i.Tenancy,
		&i.Region,
		&i.CreatedAt,
		&i.ApiSynced,
		&i.EnableIcmp,
		&i.EnableAllProtocol,
		&i.IsHomeRegion,
		&i.ParenID,
		&i.TenancyName,
		&i.TenancyDes,
		&i.AccountType,
		&i.CloudType,
		&i.RegionEn,
		&i.IDStr,
		&i.EmailAddress,
		&i.EmailEnable,
		&i.TransferStatus,
		&i.TransferAmount,
		&i.IsActive,
		&i.KeyFileBlob,
	)
	return i, err
}

const updateTenantFields = `-- name: UpdateTenantFields :exec

UPDATE tenant
SET tenancy_name = ?, tenancy_des = ?, account_type = ?, email_address = ?, is_active = ?
WHERE id = ?
`

type UpdateTenantFieldsParams struct {
	TenancyName  sql.NullString `json:"tenancy_name"`
	TenancyDes   sql.NullString `json:"tenancy_des"`
	AccountType  sql.NullString `json:"account_type"`
	EmailAddress sql.NullString `json:"email_address"`
	IsActive     sql.NullInt64  `json:"is_active"`
	ID           int64          `json:"id"`
}

const countBootInstancesByTenantId = `-- name: CountBootInstancesByTenantId :one
SELECT COUNT(*) FROM boot_instance WHERE tenant_id = ? AND status = 1
`

func (q *Queries) CountBootInstancesByTenantId(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBootInstancesByTenantId, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantChildren = `-- name: CountTenantChildren :one
SELECT COUNT(*) FROM tenant WHERE paren_id = ?
`

func (q *Queries) CountTenantChildren(ctx context.Context, parenID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenantChildren, parenID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// Extended tenant queries (Phase 9). Tenant detail, custom name, active days.
// ALL COMMENTS MUST BE ASCII-ONLY.
func (q *Queries) UpdateTenantFields(ctx context.Context, arg UpdateTenantFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantFields,
		arg.TenancyName,
		arg.TenancyDes,
		arg.AccountType,
		arg.EmailAddress,
		arg.IsActive,
		arg.ID,
	)
	return err
}
