// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpn_proxy_record.sql

package repo

import (
	"context"
	"database/sql"
)

const deleteVpnProxyRecord = `-- name: DeleteVpnProxyRecord :exec
DELETE FROM vpn_proxy_record WHERE id = ?
`

func (q *Queries) DeleteVpnProxyRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVpnProxyRecord, id)
	return err
}

const findRandomAvailableProxy = `-- name: FindRandomAvailableProxy :one

SELECT id, proxy_type, proxy_host, proxy_port, proxy_username, proxy_password, available_status, update_time, create_time FROM vpn_proxy_record
WHERE available_status = 1
ORDER BY RANDOM()
LIMIT 1
`

// VpnProxyRecord queries (Phase 3 SOCKS proxy pool). Random available pick
// parity with VpnProxyRecordRepository.findRandomAvailableRecord.
func (q *Queries) FindRandomAvailableProxy(ctx context.Context) (VpnProxyRecord, error) {
	row := q.db.QueryRowContext(ctx, findRandomAvailableProxy)
	var i VpnProxyRecord
	err := row.Scan(
		&i.ID,
		&i.ProxyType,
		&i.ProxyHost,
		&i.ProxyPort,
		&i.ProxyUsername,
		&i.ProxyPassword,
		&i.AvailableStatus,
		&i.UpdateTime,
		&i.CreateTime,
	)
	return i, err
}

const insertVpnProxyRecord = `-- name: InsertVpnProxyRecord :exec
INSERT INTO vpn_proxy_record (
    proxy_type, proxy_host, proxy_port, proxy_username, proxy_password,
    available_status, update_time, create_time
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertVpnProxyRecordParams struct {
	ProxyType       string         `json:"proxy_type"`
	ProxyHost       string         `json:"proxy_host"`
	ProxyPort       int64          `json:"proxy_port"`
	ProxyUsername   sql.NullString `json:"proxy_username"`
	ProxyPassword   sql.NullString `json:"proxy_password"`
	AvailableStatus int64          `json:"available_status"`
	UpdateTime      sql.NullString `json:"update_time"`
	CreateTime      sql.NullString `json:"create_time"`
}

func (q *Queries) InsertVpnProxyRecord(ctx context.Context, arg InsertVpnProxyRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertVpnProxyRecord,
		arg.ProxyType,
		arg.ProxyHost,
		arg.ProxyPort,
		arg.ProxyUsername,
		arg.ProxyPassword,
		arg.AvailableStatus,
		arg.UpdateTime,
		arg.CreateTime,
	)
	return err
}

const listVpnProxyRecords = `-- name: ListVpnProxyRecords :many
SELECT id, proxy_type, proxy_host, proxy_port, proxy_username, proxy_password, available_status, update_time, create_time FROM vpn_proxy_record ORDER BY id
`

func (q *Queries) ListVpnProxyRecords(ctx context.Context) ([]VpnProxyRecord, error) {
	rows, err := q.db.QueryContext(ctx, listVpnProxyRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VpnProxyRecord{}
	for rows.Next() {
		var i VpnProxyRecord
		if err := rows.Scan(
			&i.ID,
			&i.ProxyType,
			&i.ProxyHost,
			&i.ProxyPort,
			&i.ProxyUsername,
			&i.ProxyPassword,
			&i.AvailableStatus,
			&i.UpdateTime,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVpnProxyRecord = `-- name: UpdateVpnProxyRecord :exec
UPDATE vpn_proxy_record
SET proxy_type = ?, proxy_host = ?, proxy_port = ?, proxy_username = ?,
    proxy_password = ?, available_status = ?, update_time = ?
WHERE id = ?
`

type UpdateVpnProxyRecordParams struct {
	ProxyType       string         `json:"proxy_type"`
	ProxyHost       string         `json:"proxy_host"`
	ProxyPort       int64          `json:"proxy_port"`
	ProxyUsername   sql.NullString `json:"proxy_username"`
	ProxyPassword   sql.NullString `json:"proxy_password"`
	AvailableStatus int64          `json:"available_status"`
	UpdateTime      sql.NullString `json:"update_time"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateVpnProxyRecord(ctx context.Context, arg UpdateVpnProxyRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateVpnProxyRecord,
		arg.ProxyType,
		arg.ProxyHost,
		arg.ProxyPort,
		arg.ProxyUsername,
		arg.ProxyPassword,
		arg.AvailableStatus,
		arg.UpdateTime,
		arg.ID,
	)
	return err
}
